// ============================================================
//  Construtora Senger — Tabela de Preços e Disponibilidade
//  Dados consolidados a partir da Lista Senger de 10.07.26
//  Status da tabela: Julho / 2026
// ============================================================

const META = {
  mesTabela: "Agosto / 2026",
  dataTabela: "10/07/2026",
  incc: { valor: "R$ 3.377,91", variacao: "+0,62%" },
  contato: {
    telefones: ["(54) 3331-2756", "(54) 99901-3331", "(54) 98434-6602"],
    instagram: "@construtorasenger",
    site: "construtorasenger.com.br",
    endereco: "Rua Barão de Antonina, 79 — Centro, Carazinho/RS",
  },
};

// status de unidade: "disponivel" | "alugado" | "reservado" | "vendido"
// tags livres por unidade: "Decorado", "Mobiliado", "Terraço", etc.

const EMPREENDIMENTOS = [


  {
    id: "renaissance",
    nome: "Renaissance",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Pré-lançamento",
    entrega: "Pré-lançamento",
    ri: [],
    hero: "assets/ren-hero.jpg",
    logo: "assets/ren-logo.png",
    destaque: true,
    tagline: "Alto padrão Renaissance — 2 e 3 suítes, Casa Suspensa, pavimentos superiores e Duplex exclusivo.",
    condicoes: "Valores das unidades sem box de garagem — consulte opções de box disponíveis.",
    localizacao: "R. Venâncio Aires, lado ímpar — Centro, Carazinho/RS. Edifício multifamiliar residencial e comercial.",
    diferenciais: [
      { titulo: "Lazer aquático", desc: "Piscina com solário, piscina térmica/descanso e sauna." },
      { titulo: "Esporte", desc: "Quadra de beach tennis." },
      { titulo: "Fitness e bem-estar", desc: "Academia, studio de pilates, fitness center e SPA." },
      { titulo: "Convivência", desc: "Salão de festas, lounges com pergolados, terraço/área de lazer e playground." },
      { titulo: "Tipologias exclusivas", desc: "Casa Suspensa, pavimentos superiores de 3 suítes e Duplex exclusivo de 4 suítes." },
      { titulo: "Térreo comercial", desc: "Salas comerciais no pavimento térreo." },
    ],
    galeria: [
      { src: "assets/ren-planta-3s-frente-dir.webp", legenda: "Planta humanizada — 3 suítes frente (direita)" },
      { src: "assets/ren-planta-3s-frente-esq.webp", legenda: "Planta humanizada — 3 suítes frente (esquerda)" },
      { src: "assets/ren-planta-3s-superior.webp", legenda: "Planta humanizada — 3 suítes superior" },
      { src: "assets/ren-planta-2suites.jpg", legenda: "Planta humanizada — 2 suítes" },
      { src: "assets/ren-planta-504.webp", legenda: "Planta humanizada — Casa Suspensa 2 suítes (504)" },
      { src: "assets/ren-planta-604.webp", legenda: "Planta humanizada — 2 suítes (final 04)" },
    ],
    grupos: [
      {
        tipo: "Casa Suspensa (3 suítes)",
        area: "306 a 385 m² global · 208 a 280 m² privativo",
        garagem: "Box opcional (consultar)",
        obs: "Plantas exclusivas — pavimentos 4 e 13. Valores sem box de garagem.",
        unidades: [
          { apto: "401", preco: 1490000, status: "disponivel", areaUnit: "358 m² global · 258 m² privativo", tags: ["Terraço"] },
          { apto: "402", preco: 1490000, status: "disponivel", areaUnit: "385 m² global · 280 m² privativo", tags: ["Terraço"] },
          { apto: "1301", preco: 1590000, status: "disponivel", areaUnit: "306 m² global · 208 m² privativo", tags: ["Terraço"] },
          { apto: "1302", preco: 1590000, status: "disponivel", areaUnit: "306 m² global · 208 m² privativo", tags: ["Terraço"] },
        ],
      },
      {
        tipo: "3 suítes — frente",
        area: "180 m² global · 117 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-3s-frente-dir",
        obs: "Valores sem box de garagem.",
        unidades: [
          { apto: "501", preco: 1080000, status: "disponivel", areaUnit: "179 m² global · 117 m² privativo" },
          { apto: "502", preco: 1080000, status: "disponivel", areaUnit: "179 m² global · 117 m² privativo" },
          { apto: "601", preco: 1080000, status: "disponivel" },
          { apto: "602", preco: 1080000, status: "disponivel" },
          { apto: "701", preco: 1100000, status: "disponivel" },
          { apto: "702", preco: 1100000, status: "disponivel" },
          { apto: "801", preco: 1100000, status: "disponivel" },
          { apto: "802", preco: 1100000, status: "disponivel" },
          { apto: "901", preco: 1130000, status: "disponivel" },
          { apto: "902", preco: 1130000, status: "disponivel" },
          { apto: "1001", preco: 1130000, status: "disponivel" },
          { apto: "1002", preco: 1130000, status: "disponivel" },
          { apto: "1101", preco: 1150000, status: "disponivel" },
          { apto: "1102", preco: 1150000, status: "disponivel" },
          { apto: "1201", preco: 1200000, status: "disponivel" },
          { apto: "1202", preco: 1200000, status: "disponivel" },
        ],
      },
      {
        tipo: "3 suítes — pavimentos superiores",
        area: "243 m² global · 159 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-3s-superior",
        obs: "Valores sem box de garagem.",
        unidades: [
          { apto: "1401", preco: 1450000, status: "disponivel" },
          { apto: "1402", preco: 1450000, status: "disponivel" },
          { apto: "1501", preco: 1450000, status: "disponivel" },
          { apto: "1502", preco: 1450000, status: "disponivel" },
          { apto: "1601", preco: 1530000, status: "disponivel" },
          { apto: "1602", preco: 1530000, status: "disponivel" },
          { apto: "1701", preco: 1530000, status: "disponivel" },
          { apto: "1702", preco: 1530000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 suítes",
        area: "130 m² global · 86 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-2suites",
        obs: "Valores sem box de garagem.",
        unidades: [
          { apto: "503", preco: 730000, status: "disponivel" },
          { apto: "603", preco: 730000, status: "disponivel" },
          { apto: "604", preco: 730000, status: "disponivel" },
          { apto: "703", preco: 750000, status: "disponivel" },
          { apto: "704", preco: 750000, status: "disponivel" },
          { apto: "804", preco: 750000, status: "disponivel" },
          { apto: "904", preco: 780000, status: "disponivel" },
          { apto: "1003", preco: 780000, status: "disponivel" },
          { apto: "1004", preco: 780000, status: "disponivel" },
          { apto: "1103", preco: 790000, status: "disponivel" },
          { apto: "1104", preco: 790000, status: "disponivel" },
          { apto: "1203", preco: 800000, status: "disponivel" },
          { apto: "1204", preco: 800000, status: "disponivel" },
        ],
      },
      {
        tipo: "Casa Suspensa (2 suítes)",
        area: "205 m² global · 146 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-504",
        obs: "Unidade 504 — lateral direita. Valor sem box de garagem.",
        unidades: [
          { apto: "504", preco: 880000, status: "disponivel", tags: ["Terraço"] },
        ],
      },
      {
        tipo: "Salas comerciais — térreo",
        area: "175 m² global · 114 m² privativo",
        garagem: "",
        obs: "Pavimento térreo. Valores sem box de garagem.",
        unidades: [
          { apto: "Sala 04", preco: 1140000, status: "disponivel", areaUnit: "175 m² global · 114 m² privativo" },
        ],
      },
    ],
  },

  {
    id: "evolutti",
    nome: "Evolutti",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Entrega em 2028",
    entrega: "Entrega em 2028",
    ri: ["RI nº 11-47.935"],
    hero: "assets/evo-hero.jpg",
    folder: "assets/folder-evolutti.pdf",
    destaque: true,
    tagline: "O mundo evoluiu — e no Evolutti não será diferente.",
    localizacao: "Carazinho/RS — edifício de esquina com posição solar privilegiada.",
    diferenciais: [
      { titulo: "Energia renovável", desc: "Placas solares para geração de energia no consumo do condomínio." },
      { titulo: "Veículos elétricos", desc: "Estações de carregamento para carros elétricos em todos os boxes." },
      { titulo: "Comodidade", desc: "Persianas elétricas em todos os dormitórios, com acionamento por controle remoto." },
      { titulo: "Segurança", desc: "Fechaduras eletrônicas com biometria — nunca mais esqueça as chaves." },
      { titulo: "Lazer", desc: "Salão de festas, área fitness e bicicletário." },
      { titulo: "Estrutura", desc: "Moderno hall de entrada e posição solar privilegiada de edifício de esquina." },
    ],
    galeria: [
      { src: "assets/evo-1.jpg", legenda: "Fachada — entardecer" },
      { src: "assets/evo-4.jpg", legenda: "Living integrado" },
      { src: "assets/evo-5.jpg", legenda: "Sala de estar" },
      { src: "assets/evo-6.jpg", legenda: "Sala de jantar e cozinha" },
      { src: "assets/evo-7.jpg", legenda: "Cozinha" },
      { src: "assets/evo-8.jpg", legenda: "Living com sacada" },
      { src: "assets/evo-9.jpg", legenda: "Suíte" },
      { src: "assets/evo-10.jpg", legenda: "Suíte master" },
      { src: "assets/evo-11.jpg", legenda: "Dormitório" },
      { src: "assets/evo-2.jpg", legenda: "Vista aérea" },
      { src: "assets/evo-3.jpg", legenda: "Andamento da obra — mar/2025" },
      { src: "assets/evo-p2.jpg", legenda: "Planta — 2 dormitórios (1 ou 2 suítes)" },
      { src: "assets/evo-p3.jpg", legenda: "Planta — 3 dormitórios (3 suítes)" },
    ],
    grupos: [
      {
        tipo: "2 dormitórios (1 suíte)",
        area: "99 m² global · 73 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "404", preco: 730000, status: "disponivel", tags: ["Terraço"], areaUnit: "135 m² global · 104 m² privativo" },
          { apto: "504", preco: 690000, status: "disponivel" },
          { apto: "604", preco: 700000, status: "disponivel" },
          { apto: "704", preco: 710000, status: "disponivel" },
          { apto: "804", preco: 720000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 dormitórios (1 suíte)",
        area: "99 m² global · 73 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "503", preco: 740000, status: "disponivel" },
          { apto: "703", preco: 760000, status: "disponivel" },
          { apto: "803", preco: 770000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 dormitórios (2 suítes)",
        area: "118 m² global · 87 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "402", preco: 850000, status: "disponivel", tags: ["Terraço"], areaUnit: "173 m² global · 133 m² privativo" },
          { apto: "502", preco: 800000, status: "disponivel" },
        ],
      },
      {
        tipo: "3 dormitórios (3 suítes)",
        area: "179 m² global · 132 m² privativo",
        garagem: "01 box duplo",
        unidades: [
          { apto: "1002", preco: 1120000, status: "disponivel" },
          { apto: "1102", preco: 1130000, status: "disponivel" },
          { apto: "1202", preco: 1140000, status: "disponivel" },
          { apto: "1302", preco: 1150000, status: "disponivel" },
        ],
      },
    ],
  },

  {
    id: "premium-office",
    nome: "Premium Office",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "comercial",
    status: "obra",
    statusLabel: "Entrega em 2029",
    entrega: "Entrega em 2029",
    ri: ["RI nº 1-50.267"],
    hero: "assets/po-render-3.jpg",
    destaque: true,
    tagline: "Não é só um moderno centro clínico — é o futuro da área da saúde de Carazinho.",
    condicoes: "Entrada + saldo direto com a construtora.",
    localizacao: "Rua Cipriano da Luz — em frente à Praça do Hospital de Clínicas de Carazinho.",
    diferenciais: [
      { titulo: "Rooftop", desc: "Conforto e vista privilegiada que transformam a espera do paciente em uma experiência única." },
      { titulo: "Sunset Lounge", desc: "Espaço privativo dos profissionais, para relaxar e recarregar entre atendimentos." },
      { titulo: "Elevador para maca", desc: "Dois elevadores, sendo um deles preparado para maca." },
      { titulo: "Hall imponente", desc: "Pé direito duplo, com acesso para veículos e ambulâncias na entrada." },
      { titulo: "Personalização", desc: "Possibilidade de unir salas, ajustando o tamanho à sua necessidade." },
      { titulo: "Box de garagem", desc: "Todas as salas com box de garagem." },
      { titulo: "WCs sociais acessíveis", desc: "Banheiros sociais com acessibilidade em todos os pavimentos." },
      { titulo: "Design em LED", desc: "Linhas iluminadas que destacam o edifício à noite." },
    ],
    galeria: [
      { src: "assets/po-render-1.jpg", legenda: "Fachada — vista diurna" },
      { src: "assets/po-render-2.jpg", legenda: "Fachada — entardecer" },
      { src: "assets/po-obra1.jpg", legenda: "Fachada completa" },
      { src: "assets/po-garagem.jpg", legenda: "Volumetria do edifício" },
      { src: "assets/po-hall.jpg", legenda: "Hall de entrada — pé direito duplo" },
      { src: "assets/po-int1.jpg", legenda: "Hall — pé direito duplo" },
      { src: "assets/po-int2.jpg", legenda: "Recepção Premium Office" },
      { src: "assets/po-r4.jpg", legenda: "Escritório / consultório — projeto" },
      { src: "assets/po-r5.jpg", legenda: "Escritório / consultório — projeto" },
      { src: "assets/po-r6.jpg", legenda: "Sala com divisórias de vidro" },
      { src: "assets/po-rooftop.jpg", legenda: "Rooftop" },
      { src: "assets/po-lounge.jpg", legenda: "Sunset Lounge" },
      { src: "assets/po-obra2.jpg", legenda: "Terraço / rooftop" },
      { src: "assets/po-vaga.jpg", legenda: "Garagem coberta" },
      { src: "assets/po-aerial.jpg", legenda: "Vista aérea" },
      { src: "assets/po-aerial2.jpg", legenda: "Vista aérea — bairro" },
      { src: "assets/po-loc.jpg", legenda: "Localização — em frente à Praça do Hospital de Clínicas" },
      { src: "assets/po-planta.jpg", legenda: "Planta — Rua Cipriano da Luz" },
      { src: "assets/po-map.jpg", legenda: "Mapa — Rua Cipriano da Luz" },
    ],
    grupos: [
      {
        tipo: "Sala comercial",
        area: "76 m² global · 43 m² privativo",
        garagem: "01 vaga de garagem",
        unidades: [{ apto: "705", preco: 600000, status: "disponivel" }],
      },
      {
        tipo: "Sala comercial",
        area: "54 m² global · 31 m² privativo",
        garagem: "01 vaga de garagem",
        unidades: [{ apto: "803", preco: 480000, status: "disponivel" }],
      },
      {
        tipo: "Sala comercial",
        area: "115 m² global · 65 m² privativo",
        garagem: "01 vaga de garagem",
        unidades: [
          { apto: "801", preco: 850000, status: "disponivel" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "72 m² global · 40 m² privativo",
        garagem: "01 vaga de garagem",
        unidades: [
          { apto: "304", preco: 560000, status: "disponivel" },
          { apto: "804", preco: 600000, status: "disponivel" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "129 m² global · 73 m² privativo",
        garagem: "01 vaga de garagem",
        unidades: [{ apto: "802", preco: 880000, status: "disponivel" }],
      },
      {
        tipo: "Salas comerciais — pavimento térreo",
        area: "Áreas variadas",
        garagem: "01 vaga de garagem por sala",
        unidades: [
          { apto: "201", preco: 1140000, status: "disponivel", areaUnit: "160 m² global · 90 m² privativo" },
          { apto: "202", preco: 1010000, status: "disponivel", areaUnit: "139 m² global · 78 m² privativo" },
          { apto: "203", preco: 660000, status: "disponivel", areaUnit: "88 m² global · 49 m² privativo" },
        ],
      },
    ],
  },

  {
    id: "boulevard",
    nome: "Boulevard Residence",
    confirmado: true,
    cidade: "Ibirubá/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Entrega em 2028",
    entrega: "Entrega em 2028",
    ri: ["RI nº 1-50.267"],
    hero: "assets/bv-hero.jpg",
    destaque: true,
    tagline: "Onde morar é sinônimo de bem-estar.",
    localizacao: "Rua Getúlio Vargas — em frente à Praça Gen. Osório, Ibirubá/RS.",
    diferenciais: [
      { titulo: "Localização privilegiada", desc: "No coração de Ibirubá, em frente à Praça Gen. Osório, com fácil acesso a comércio, serviços e lazer." },
      { titulo: "Qualidade e bem-estar", desc: "Acabamentos de alto padrão e ambientes integrados, pensados para conforto, segurança e praticidade." },
      { titulo: "Lazer completo", desc: "Piscina, estar de fogo, espaço fitness, playground, espaço pub com churrasqueira e jogos, salão de festas + espaço kids." },
    ],
    galeria: [
      { src: "assets/bv-1.jpg", legenda: "Fachada" },
      { src: "assets/bv-2.jpg", legenda: "Área de lazer" },
      { src: "assets/bv-3.jpg", legenda: "Piscina" },
      { src: "assets/bv-4.jpg", legenda: "Ambientes" },
      { src: "assets/bv-9.jpg", legenda: "Lazer" },
      { src: "assets/bv-5.jpg", legenda: "Ambientes" },
      { src: "assets/bv-6.jpg", legenda: "Espaço pub" },
      { src: "assets/bv-7.jpg", legenda: "Salão de festas" },
      { src: "assets/bv-8.jpg", legenda: "Espaço kids" },
      { src: "assets/bv-planta.jpg", legenda: "Planta — pavimento" },
      { src: "assets/bv-planta-lazer.jpg", legenda: "Planta — área de lazer" },
      { src: "assets/bv-folder.jpg", legenda: "Folder do empreendimento" },
      { src: "assets/bv-map.jpg", legenda: "Rua Getúlio Vargas — frente à Praça Gen. Osório" },
    ],
    grupos: [
      {
        tipo: "3 suítes + lavabo",
        area: "212 m² global · 150 m² privativo",
        garagem: "Box duplo",
        unidades: [
          { apto: "501", preco: 1420000, status: "disponivel" },
          { apto: "801", preco: 1440000, status: "disponivel" },
          { apto: "901", preco: 1460000, status: "disponivel" },
        ],
      },
      {
        tipo: "3 suítes + lavabo",
        area: "212 m² global · 150 m² privativo",
        garagem: "Box duplo",
        obs: "Terraço: 246 m² global · 177 m² privativo.",
        unidades: [
          { apto: "602", preco: 1440000, status: "disponivel" },
          { apto: "702", preco: 1460000, status: "disponivel" },
          { apto: "902", preco: 1480000, status: "disponivel" },
          { apto: "1002", preco: 1500000, status: "disponivel" },
          { apto: "1102", preco: 1520000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 suítes + lavabo",
        area: "131 m² global · 93 m² privativo",
        garagem: "01 box de garagem",
        obs: "Terraço: 165 m² global · 121 m² privativo.",
        unidades: [
          { apto: "304", preco: 870000, status: "disponivel", tags: ["Terraço"] },
          { apto: "404", preco: 850000, status: "disponivel" },
          { apto: "504", preco: 860000, status: "disponivel" },
          { apto: "704", preco: 880000, status: "disponivel" },
          { apto: "904", preco: 900000, status: "disponivel" },
          { apto: "1104", preco: 920000, status: "disponivel" },
          { apto: "1204", preco: 930000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 dormitórios (1 suíte)",
        area: "127 m² global · 91 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "403", preco: 820000, status: "disponivel" },
          { apto: "503", preco: 830000, status: "disponivel" },
          { apto: "603", preco: 840000, status: "disponivel" },
          { apto: "703", preco: 850000, status: "disponivel" },
          { apto: "803", preco: 860000, status: "disponivel" },
          { apto: "903", preco: 870000, status: "disponivel" },
          { apto: "1003", preco: 880000, status: "disponivel" },
          { apto: "1103", preco: 890000, status: "disponivel" },
          { apto: "1203", preco: 900000, status: "disponivel" },
        ],
      },
    ],
  },

  {
    id: "personalite",
    nome: "Personalité",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 11-38.407"],
    hero: "assets/perso-1.jpg",
    destaque: true,
    tagline: "Alto padrão Personalité — venha morar com estilo.",
    localizacao: "Região central de Carazinho/RS — edifício de esquina com posição solar privilegiada.",
    diferenciais: [
      { titulo: "Lazer", desc: "Piscina aquecida e 2 salões de festas completos, com terraço e acesso à piscina." },
      { titulo: "Conforto", desc: "Acabamento refinado, aquecimento a gás, 2 elevadores e sacada com churrasqueira a carvão." },
      { titulo: "Alto padrão", desc: "Amplos apartamentos, hall de entrada refinado, porcelanato e gesso em todo o apartamento." },
      { titulo: "Estrutura", desc: "Medição individual de água, luz e gás; detalhes em vidro laminado; esquadrias de alumínio anodizado." },
    ],
    galeria: [
      { src: "assets/perso-2.jpg", legenda: "Hall de entrada" },
      { src: "assets/perso-4.jpg", legenda: "Hall — pé direito alto" },
      { src: "assets/perso-3.jpg", legenda: "Salão de festas" },
      { src: "assets/perso-5.jpg", legenda: "Piscina aquecida" },
      { src: "assets/perso-7.jpg", legenda: "Salão de festas com terraço" },
      { src: "assets/perso-6.jpg", legenda: "Apartamento — cozinha integrada" },
      { src: "assets/perso-planta.jpg", legenda: "Planta — 3 suítes + lavabo" },
      { src: "assets/perso-map.jpg", legenda: "Localização — Centro" },
    ],
    grupos: [
      {
        tipo: "3 suítes + lavabo",
        area: "172 m² global · 132 m² privativo",
        garagem: "Box duplo",
        unidades: [
          { apto: "602", preco: 1310000, status: "disponivel" },
          { apto: "902", preco: 1450000, status: "disponivel", tags: ["Mobiliado"] },
        ],
      },
    ],
  },

  {
    id: "prime",
    nome: "Prime",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 2-45.162"],
    hero: "assets/prime-hero.jpg",
    destaque: true,
    tagline: "Prime, no coração da cidade — qualidade de vida todos os dias.",
    localizacao: "R. Venâncio Aires, 121 — Centro, Carazinho/RS. Edifício de esquina, ao lado de mercado, escolas e farmácia.",
    diferenciais: [
      { titulo: "Localização", desc: "Edifício de esquina com posição solar privilegiada, ao lado de mercado, escolas e farmácia." },
      { titulo: "Alto padrão", desc: "Amplos apartamentos com living integrado, churrasqueira a carvão e vista para a praça central." },
      { titulo: "Lazer e convivência", desc: "Salão de festas com terraço e hall de entrada com pé direito alto." },
      { titulo: "Conforto", desc: "Acabamento refinado, aquecimento a gás, 2 elevadores, persianas elétricas e fechadura biométrica." },
    ],
    galeria: [
      { src: "assets/prime-4.jpg", legenda: "Fachada — edifício de esquina" },
      { src: "assets/prime-1.jpg", legenda: "Apartamento decorado — living" },
      { src: "assets/prime-2.jpg", legenda: "Apartamento decorado — estar" },
      { src: "assets/prime-3.jpg", legenda: "Apartamento decorado — suíte" },
      { src: "assets/prime-6.jpg", legenda: "Hall de entrada" },
      { src: "assets/prime-5.jpg", legenda: "Fechadura biométrica" },
      { src: "assets/prime-planta.jpg", legenda: "Planta — 3 dormitórios (2 suítes)" },
      { src: "assets/prime-map.jpg", legenda: "R. Venâncio Aires, 121 — Centro" },
    ],
    grupos: [
      {
        tipo: "3 dormitórios (2 suítes)",
        area: "124 m² global · 96 m² privativo",
        garagem: "Box duplo",
        unidades: [{ apto: "303", preco: 1180000, status: "disponivel", tags: ["Decorado"] }],
      },
    ],
  },

  {
    id: "quality",
    nome: "Senger Quality Residence",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 2-34.244"],
    hero: "assets/qual-1.jpg",
    destaque: true,
    tagline: "Piscina, academia e 3 salões de festas — pronto para morar e financiável.",
    localizacao: "Carazinho/RS — excelente localização.",
    diferenciais: [
      { titulo: "Lazer", desc: "Piscina na área social, junto ao salão de festas." },
      { titulo: "Área fitness", desc: "Academia completa." },
      { titulo: "Salões de festas", desc: "3 salões de festas — dois internos e um externo." },
      { titulo: "Praticidade", desc: "Lavanderia coletiva com área para estender roupas." },
      { titulo: "Acabamento", desc: "Gesso em todo o apartamento, porcelanato e grafiato na parte externa." },
      { titulo: "Segurança", desc: "Hall de entrada e estrutura com segurança." },
    ],
    galeria: [
      { src: "assets/qual-2.jpg", legenda: "Piscina" },
      { src: "assets/qual-3.jpg", legenda: "Academia" },
      { src: "assets/qual-9.jpg", legenda: "Apartamento — living com móveis" },
      { src: "assets/qual-10.jpg", legenda: "Dormitório" },
      { src: "assets/qual-4.jpg", legenda: "Área social" },
      { src: "assets/qual-5.jpg", legenda: "Área social" },
      { src: "assets/qual-6.jpg", legenda: "Área social" },
      { src: "assets/qual-7.jpg", legenda: "Salão de festas" },
      { src: "assets/qual-8.jpg", legenda: "Salão de festas" },
      { src: "assets/qual-planta-57.jpg", legenda: "Planta — 2 dormitórios (57m² global)" },
      { src: "assets/qual-planta-69.jpg", legenda: "Planta — 2 dormitórios (69m² global)" },
      { src: "assets/qual-planta-3d.jpg", legenda: "Planta — 3 dormitórios (1 suíte)" },
      { src: "assets/int-cozinha-1.jpg", legenda: "Cozinha com móveis planejados" },
      { src: "assets/qual-map.jpg", legenda: "Localização" },
    ],
    grupos: [
      {
        tipo: "2 dormitórios c/ móveis",
        area: "57 m² global · 43 m² privativo",
        garagem: "Box de garagem",
        planta: "qual-planta-57",
        unidades: [{ apto: "802A", preco: 430000, status: "disponivel" }],
      },
      {
        tipo: "2 dormitórios c/ móveis",
        area: "69 m² global · 53 m² privativo",
        garagem: "Box de garagem",
        planta: "qual-planta-69",
        unidades: [{ apto: "801B", preco: 530000, status: "disponivel" }],
      },
      {
        tipo: "2 dormitórios — já alugados",
        area: "69 m² global · 53 m² privativo",
        garagem: "Box de garagem",
        planta: "qual-planta-69",
        obs: "Aluguel R$ 1.400,00 · Condomínio e IPTU por conta do inquilino.",
        unidades: [
          { apto: "301B", preco: 470000, status: "alugado" },
          { apto: "601B", preco: 490000, status: "alugado" },
          { apto: "701B", preco: 500000, status: "alugado" },
        ],
      },
      {
        tipo: "3 dormitórios — já alugados",
        area: "87 m² global · 66 m² privativo",
        garagem: "Box de garagem",
        planta: "qual-planta-3d",
        obs: "Aluguel R$ 1.600,00 · Condomínio e IPTU por conta do inquilino.",
        unidades: [
          { apto: "501A", preco: 580000, status: "alugado" },
          { apto: "601A", preco: 590000, status: "alugado" },
          { apto: "801A", preco: 610000, status: "alugado" },
        ],
      },
      {
        tipo: "3 dormitórios (1 suíte) c/ móveis",
        area: "87 m² global · 66 m² privativo",
        garagem: "Box de garagem",
        planta: "qual-planta-3d",
        unidades: [
          { apto: "201A", preco: 550000, status: "disponivel" },
          { apto: "401A", preco: 580000, status: "disponivel", tags: ["Mobiliado"] },
          { apto: "701A", preco: 590000, status: "disponivel" },
        ],
      },
    ],
  },

  {
    id: "nova-vila-rica-iii",
    nome: "Loteamento Nova Vila Rica III",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "terreno",
    status: "obra",
    statusLabel: "Entrega em 2027",
    entrega: "Entrega em 2027",
    ri: [],
    hero: "assets/aerial-vilarica.jpg",
    logo: "assets/nvr3-logo.jpg",
    destaque: true,
    tagline: "Lotes prontos para construir, no novo loteamento Nova Vila Rica III.",
    condicoes: "Entrada de 20% + saldo direto com a construtora. Construção após quitação ou financiamento bancário.",
    localizacao: "Carazinho/RS — Ruas Laranjeira, Figueira, Jatobá, J. Kennedy e H. T. Schutz.",
    galeria: [
      { src: "assets/nvr3-mapa.jpg", legenda: "Mapa de lotes e disponibilidade" },
      { src: "assets/nvr3-urb.jpg", legenda: "Projeto de urbanismo" },
      { src: "assets/nvr3-planta.jpg", legenda: "Planta de lotes" },
    ],
    terrenos: [
      { quadra: "77", numero: "91", rua: "Laranjeira", area: 348, preco: 75000 },
      { quadra: "77", numero: "98", rua: "Laranjeira", area: 348, preco: 75000 },
      { quadra: "77", numero: "100", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "101", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "103", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "104", rua: "Laranjeira", area: 314.4, preco: 85000 },
      { quadra: "77", numero: "105", rua: "Laranjeira", area: 468, preco: 115000 },
      { quadra: "77", numero: "106", rua: "Figueira", area: 312, preco: 85000 },
      { quadra: "77", numero: "107", rua: "Figueira", area: 312, preco: 85000 },
      { quadra: "147", numero: "16", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "17", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "18", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "20", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "21", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "22", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "23", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "24", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "25", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "26", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "27", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "28", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "29", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "30", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "155", numero: "1", rua: "J. Kennedy", area: 445.5, preco: 115000 },
      { quadra: "155", numero: "4", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "5", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "6", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "8", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "9", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "12", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "13", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "14", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "15", rua: "Jatobá", area: 324, preco: 90000 },
      { quadra: "155", numero: "16", rua: "Laranjeira", area: 324, preco: 100000 },
      { quadra: "155", numero: "17", rua: "Laranjeira", area: 270, preco: 85000 },
      { quadra: "155", numero: "18", rua: "Laranjeira", area: 270, preco: 85000 },
      { quadra: "155", numero: "22", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "23", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "24", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "25", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "26", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "27", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "28", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "29", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "30", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "31", rua: "J. Kennedy", area: 423.9, preco: 115000 },
      { quadra: "157", numero: "16", rua: "H. T. Schutz", area: 360, preco: 120000 },
      { quadra: "157", numero: "19", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "20", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "21", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "22", rua: "Jatobá", area: 323.35, preco: 115000 },
      { quadra: "157", numero: "23", rua: "J. Kennedy", area: 357.6, preco: 100000 },
      { quadra: "157", numero: "24", rua: "J. Kennedy", area: 250.85, preco: 95000 },
      { quadra: "157", numero: "25", rua: "Laranjeira", area: 297.6, preco: 115000 },
      { quadra: "157", numero: "26", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "27", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "28", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "29", rua: "Laranjeira", area: 205, preco: 65000 },
      { quadra: "157", numero: "33", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "34", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "35", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "36", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "37", rua: "J. Kennedy", area: 333.45, preco: 115000 },
    ],
    grupos: [],
  },

  {
    id: "nova-vila-rica",
    nome: "Loteamento Nova Vila Rica I & II",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "terreno",
    status: "pronto",
    statusLabel: "Prontos para construir",
    entrega: "Prontos para construir · Financiáveis MCMV I & II",
    ri: [],
    hero: "assets/aerial-vilarica-i-ii.jpg",
    galeria: [],
    terrenos: [
      { lote: "Nova Vila Rica I", quadra: "144", numero: "01", rua: "Alberto Graeff", area: 325, preco: 125000 },
      { lote: "Nova Vila Rica I", quadra: "145", numero: "01", rua: "Alberto Graeff", area: 345, preco: 125000 },
      { lote: "Nova Vila Rica I", quadra: "145", numero: "03", rua: "Alberto Graeff", area: 320, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "146", numero: "01", rua: "Figueira", area: 385, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "147", numero: "09", rua: "Alberto Graeff", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "147", numero: "05", rua: "Alberto Graeff", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "77", numero: "50", rua: "Acácia", area: 342, preco: 100000 },
      { lote: "Nova Vila Rica II", quadra: "77", numero: "51", rua: "Acácia", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "145", numero: "10", rua: "Acácia", area: 400, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "145", numero: "18", rua: "Figueira", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "146", numero: "22", rua: "Figueira", area: 1420, preco: 305000 },
    ],
    grupos: [],
  },

  {
    id: "outros",
    nome: "Outros Imóveis",
    confirmado: true,
    cidade: "Santa Maria/RS · Carazinho/RS",
    categoria: "outros",
    status: "pronto",
    statusLabel: "Disponível",
    entrega: "Pronto",
    ri: [],
    hero: "assets/gabro-predio.png",
    galeria: [],
    outros: [
      {
        nome: "Residencial Gabro",
        local: "Centro de Santa Maria/RS",
        descricao:
          "Apto 604 — 2 dormitórios, sala de estar com sacada, cozinha integrada com lavanderia, churrasqueira e box de garagem nº 38. Posição lateral com sol da manhã.",
        area: "82 m² global · 60 m² privativo",
        preco: 475000,
        precoPrefixo: "de",
        status: "disponivel",
      },
      {
        nome: "Edifício Campos Elísios",
        local: "Centro de Carazinho/RS",
        descricao:
          "3 dormitórios (1 suíte com closet), 2 banheiros, 3 sacadas, copa, cozinha, churrasqueira e despensa. Edifício de esquina, excelente localização, a uma quadra da avenida. Box duplo.",
        area: "145 m² privativo",
        preco: 495000,
        status: "alugado",
        obs: "Alugado por R$ 2.400,00.",
      },
      {
        nome: "Terreno Loteamento Jardim América",
        local: "Não-Me-Toque/RS",
        descricao:
          "Em frente à Stara, saída para Lagoa dos 3 Cantos. Na 2ª quadra, com linda vista do alto do loteamento. Quadra 490, Lote 241, 16m x 24,75m.",
        area: "396 m²",
        preco: 148000,
        status: "disponivel",
      },
      {
        nome: "Terreno Bairro Vila Aurora",
        local: "Carazinho/RS",
        descricao:
          "Altos da Princesa com Vila Rica, a uma quadra da Siqueira Campos, perto do posto de combustível. Fundos e uma das laterais já com muro. Rua do Carmo, 13m x 33m.",
        area: "429 m²",
        preco: 135000,
        status: "disponivel",
      },
    ],
    grupos: [],
  },
];

// Localização (link Google Maps) por empreendimento
const LOCAIS = {
  quality: { mapsUrl: "https://www.google.com/maps?q=-28.287054,-52.797171" },
  prime: { mapsUrl: "https://www.google.com/maps?q=R.%20Ven%C3%A2ncio%20Aires%2C%20121%2C%20Centro%2C%20Carazinho%20-%20RS" },
  renaissance: { mapsUrl: "https://www.google.com/maps?q=R.%20Ven%C3%A2ncio%20Aires%2C%20Centro%2C%20Carazinho%20-%20RS" },
  personalite: { mapsUrl: "https://www.google.com/maps?q=-28.284667,-52.791722" },
  evolutti: { mapsUrl: "https://www.google.com/maps?q=-28.282806,-52.784389" },
  boulevard: { mapsUrl: "https://www.google.com/maps?q=Pra%C3%A7a%20General%20Os%C3%B3rio%2C%20Ibirub%C3%A1%20-%20RS" },
  "premium-office": { mapsUrl: "https://www.google.com/maps?q=-28.283750,-52.796917" },
};

window.SENGER = { META, EMPREENDIMENTOS, LOCAIS };

