// ============================================================
//  Construtora Senger — Tabela de Preços e Disponibilidade
//  Dados consolidados a partir da Lista Senger de 10.07.26
//  Status da tabela: Julho / 2026
// ============================================================

const META = {
  mesTabela: "Agosto / 2026",
  dataTabela: "10/07/2026",
  incc: { valor: "R$ 3.377,91", variacao: "+0,62%" },
  contato: {
    telefones: ["(54) 3331-2756", "(54) 99901-3331", "(54) 98434-6602"],
    instagram: "@construtorasenger",
    site: "construtorasenger.com.br",
    endereco: "Rua Barão de Antonina, 79 — Centro, Carazinho/RS",
  },
};

// status de unidade: "disponivel" | "alugado" | "vendido"
// Nao existe "reservado": a construtora nao reserva unidades.
// tags livres por unidade: "Decorado", "Mobiliado", "Casa Suspensa", etc.

const EMPREENDIMENTOS = [


  {
    id: "renaissance",
    nome: "Renaissance",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Pré-lançamento",
    entrega: "Pré-lançamento com entrega em 5 anos",
    ri: [],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "2 suítes": { simples: 1 },
      "3 suítes — frente": { duplo: 1 },
      "3 suítes — superiores": { duplo: 1, simples: 1 },
      // A cobertura levou os box 116 a 119 — quatro simples, ja vendidos com ela.
      "18º pavimento": { simples: 4 },
    },
    hero: "assets/ren-hero.webp",
    folder: "",
    video: "",
    logo: "assets/ren-logo.webp",
    destaque: true,
    tagline: "Alto padrão Renaissance — 2 e 3 suítes, Casa Suspensa, pavimentos superiores e Duplex exclusivo.",
    localizacao: "R. Venâncio Aires — Centro, Carazinho/RS.",
    diferenciais: [
      { titulo: "Wellness Renaissance Experience", desc: "Ampla área no 4º pavimento dedicada ao lazer, à saúde e à convivência." },
      { titulo: "Esporte", desc: "Quadra de areia para esportes." },
      { titulo: "Lazer aquático", desc: "Duas piscinas aquecidas, uma na área externa e outra interna." },
      { titulo: "Fitness e bem-estar", desc: "Área fitness, espaço wellness com área para pilates e sauna." },
      { titulo: "Convivência", desc: "Salão de festas, estar do fogo e playground." },
      { titulo: "Entrada", desc: "Hall de entrada luxuoso, com pé-direito duplo." },
      // naMensagem: false -> fica na ficha do empreendimento, fora da mensagem da unidade.
      { titulo: "Espaço Care", desc: "Ambientes dedicados ao atendimento de profissionais da área da saúde e bem-estar.", naMensagem: false },
      { titulo: "Tipologias exclusivas", desc: "Casa Suspensa, pavimentos superiores de 3 suítes e Duplex exclusivo de 4 suítes.", naMensagem: false },
      { titulo: "Térreo comercial", desc: "Salas comerciais no pavimento térreo.", naMensagem: false },
    ],
    galeria: [
      { src: "assets/ren-lazer-piscina-externa.webp", legenda: "Piscina externa aquecida" },
      { src: "assets/ren-lazer-piscina-interna.webp", legenda: "Piscina interna coberta" },
      { src: "assets/ren-lazer-quadra.webp", legenda: "Quadra de areia" },
      { src: "assets/ren-lazer-salao-festas.webp", legenda: "Salão de festas" },
      { src: "assets/ren-lazer-estar-fogo.webp", legenda: "Estar do fogo" },
      { src: "assets/ren-lazer-pilates.webp", legenda: "Espaço wellness e pilates" },
      { src: "assets/ren-lazer-academia.webp", legenda: "Área fitness" },
      { src: "assets/ren-lazer-playground.webp", legenda: "Playground" },
      { src: "assets/ren-planta-3s-frente-dir.webp", legenda: "Planta humanizada — 3 suítes frente (direita)" },
      { src: "assets/ren-planta-3s-frente-esq.webp", legenda: "Planta humanizada — 3 suítes frente (esquerda)" },
      { src: "assets/ren-planta-3s-superior.webp", legenda: "Planta humanizada — 3 suítes superior" },
      { src: "assets/ren-planta-2suites.webp", legenda: "Planta humanizada — 2 suítes" },
      { src: "assets/ren-planta-504.webp", legenda: "Planta humanizada — Casa Suspensa 2 suítes (504)" },
      { src: "assets/ren-planta-401.webp", legenda: "Planta humanizada — Casa Suspensa 3 suítes (401)" },
      { src: "assets/ren-planta-402.webp", legenda: "Planta humanizada — Casa Suspensa 3 suítes (402)" },
      { src: "assets/ren-planta-1301.webp", legenda: "Planta humanizada — Casa Suspensa 3 suítes (1301)" },
      { src: "assets/ren-planta-1302.webp", legenda: "Planta humanizada — Casa Suspensa 3 suítes (1302)" },
      { src: "assets/ren-planta-604.webp", legenda: "Planta humanizada — 2 suítes (final 04)" },
      // Planta baixa do terreo: e a planta das salas comerciais. Nao e
      // humanizada, entao vai marcada como tecnica — o visor separa as duas.
      { src: "assets/ren-planta-comercial-terreo.webp", legenda: "Planta baixa — salas comerciais do térreo", tecnica: true },
    ],
    grupos: [
      {
        tipo: "Casa Suspensa (3 suítes)",
        area: "306 a 385 m² global · 208 a 280 m² privativo",
        garagem: "Box opcional (consultar)",
        obs: "Plantas exclusivas — pavimentos 4 e 13. Valor sem box de garagem.",
        unidades: [
          { apto: "401", preco: 1490000, status: "disponivel", areaUnit: "358 m² global · 258 m² privativo", planta: "ren-planta-401", estoque: "3 suítes — frente" },
          { apto: "402", preco: 1490000, status: "disponivel", areaUnit: "385 m² global · 280 m² privativo", planta: "ren-planta-402", estoque: "3 suítes — frente" },
          { apto: "1301", preco: 1590000, status: "disponivel", areaUnit: "306 m² global · 208 m² privativo", planta: "ren-planta-1301", estoque: "3 suítes — superiores" },
          { apto: "1302", preco: 1590000, status: "disponivel", areaUnit: "306 m² global · 208 m² privativo", planta: "ren-planta-1302", estoque: "3 suítes — superiores" },
        ],
      },
      {
        tipo: "3 suítes — frente",
        area: "180 m² global · 117 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-3s-frente-dir",
        obs: "Valor sem box de garagem.",
        unidades: [
          { apto: "501", preco: 1080000, status: "disponivel", areaUnit: "179 m² global · 117 m² privativo" },
          { apto: "502", preco: 1080000, status: "disponivel", areaUnit: "179 m² global · 117 m² privativo" },
          { apto: "601", preco: 1080000, status: "disponivel" },
          { apto: "602", preco: 1080000, status: "disponivel" },
          { apto: "701", preco: 1100000, status: "disponivel" },
          { apto: "702", preco: 1100000, status: "disponivel" },
          { apto: "801", preco: 1100000, status: "disponivel" },
          { apto: "802", preco: 1100000, status: "disponivel" },
          { apto: "901", preco: 1130000, status: "disponivel" },
          { apto: "902", preco: 1130000, status: "disponivel" },
          { apto: "1001", preco: 1130000, status: "disponivel" },
          { apto: "1002", preco: 1130000, status: "disponivel" },
          { apto: "1101", preco: 1150000, status: "disponivel" },
          { apto: "1102", preco: 1150000, status: "disponivel" },
          { apto: "1201", preco: 1200000, status: "disponivel" },
          { apto: "1202", preco: 1200000, status: "disponivel" },
        ],
      },
      {
        tipo: "3 suítes — pavimentos superiores",
        // No cartao do painel a linha e mais curta, para nao quebrar em duas.
        estoque: "3 suítes — superiores",
        area: "243 m² global · 159 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-3s-superior",
        obs: "Pé-direito livre de 3 metros. Valor sem box de garagem.",
        unidades: [
          { apto: "1401", preco: 1450000, status: "disponivel" },
          { apto: "1402", preco: 1450000, status: "disponivel" },
          { apto: "1501", preco: 1450000, status: "disponivel" },
          { apto: "1502", preco: 1450000, status: "disponivel" },
          { apto: "1601", preco: 1530000, status: "disponivel" },
          { apto: "1602", preco: 1530000, status: "disponivel" },
          { apto: "1701", preco: 1530000, status: "disponivel" },
          { apto: "1702", preco: 1530000, status: "disponivel" },
        ],
      },
      {
        // Cobertura do 18o pavimento, ja vendida. O 1801 e a uniao do 1801 com
        // o 1802 num apartamento so, e levou consigo os box 116 a 119.
        // Vendido nao leva numero de dormitorios — a planta costuma ser
        // modificada pelo comprador. Como e a unica unidade do grupo, ele nao
        // aparece no site.
        tipo: "18º pavimento",
        area: "490 m² global · 332 m² privativo",
        garagem: "Box opcional (consultar)",
        // Nao ha planta a mostrar: a cobertura foi vendida e a planta e a que o
        // comprador desenhar. Sem este recado, quem abrisse o link da unidade
        // veria as plantas de todas as outras tipologias no lugar.
        plantaNota: "Planta personalizada — consulte",
        unidades: [
          { apto: "1801", status: "vendido" },
        ],
      },
      {
        tipo: "2 suítes",
        area: "130 m² global · 86 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-2suites",
        obs: "Valor sem box de garagem.",
        unidades: [
          { apto: "503", preco: 730000, status: "disponivel" },
          { apto: "603", preco: 730000, status: "disponivel" },
          { apto: "604", preco: 730000, status: "disponivel" },
          { apto: "703", preco: 750000, status: "disponivel" },
          { apto: "704", preco: 750000, status: "disponivel" },
          { apto: "803", status: "vendido" },
          { apto: "804", preco: 750000, status: "disponivel" },
          { apto: "903", status: "vendido" },
          { apto: "904", preco: 780000, status: "disponivel" },
          { apto: "1003", preco: 780000, status: "disponivel" },
          { apto: "1004", preco: 780000, status: "disponivel" },
          { apto: "1103", preco: 790000, status: "disponivel" },
          { apto: "1104", preco: 790000, status: "disponivel" },
          { apto: "1203", preco: 800000, status: "disponivel" },
          { apto: "1204", preco: 800000, status: "disponivel" },
        ],
      },
      {
        tipo: "Casa Suspensa (2 suítes)",
        area: "205 m² global · 146 m² privativo",
        garagem: "Box opcional (consultar)",
        planta: "ren-planta-504",
        obs: "Unidade 504 — lateral direita. Valor sem box de garagem.",
        unidades: [
          { apto: "504", preco: 880000, status: "disponivel", estoque: "2 suítes" },
        ],
      },
      {
        tipo: "Salas comerciais — térreo",
        // No painel, a contagem de estoque chama de "Sala comercial": nao e
        // apartamento e nao entra na divisao das vagas de garagem.
        estoque: "Sala comercial",
        area: "175 m² global · 114 m² privativo",
        garagem: "",
        planta: "ren-planta-comercial-terreo",
        obs: "Pavimento térreo. Valor sem box de garagem.",
        unidades: [
          { apto: "Sala 01", status: "vendido", areaUnit: "200 m² global · 131 m² privativo" },
          { apto: "Sala 02", status: "vendido", areaUnit: "177 m² global · 115 m² privativo" },
          { apto: "Sala 03", status: "vendido", areaUnit: "270 m² global · 176 m² privativo", obs: "Com mesanino" },
          { apto: "Sala 04", preco: 1140000, status: "disponivel", areaUnit: "175 m² global · 114 m² privativo" },
        ],
      },
    ],
    // Box de garagem avulsos, nos tres pavimentos. Nao aparecem no site publico
    // (app.js so le grupos/terrenos/outros) — sao usados so pelo painel.
    boxes: [
      { box: "101", vagas: 2, areaPriv: 34.96, areaGlobal: 44.22, status: "disponivel" },
      { box: "102", vagas: 1, areaPriv: 17.98, areaGlobal: 22.74, status: "disponivel" },
      { box: "103", vagas: 1, areaPriv: 17.98, areaGlobal: 22.74, status: "disponivel" },
      { box: "104", vagas: 1, areaPriv: 19.04, areaGlobal: 24.08, status: "vendido", apto: "803" },
      { box: "105", vagas: 1, areaPriv: 16.94, areaGlobal: 21.43, status: "vendido", apto: "903" },
      { box: "106", vagas: 2, areaPriv: 35.56, areaGlobal: 44.98, status: "disponivel" },
      { box: "107", vagas: 2, areaPriv: 36.06, areaGlobal: 45.61, status: "disponivel" },
      { box: "108", vagas: 1, areaPriv: 20.14, areaGlobal: 25.48, status: "disponivel" },
      { box: "109", vagas: 1, areaPriv: 21.76, areaGlobal: 27.52, status: "disponivel" },
      { box: "110", vagas: 2, areaPriv: 35.14, areaGlobal: 44.45, status: "disponivel" },
      { box: "111", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "112", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "113", vagas: 1, areaPriv: 18.76, areaGlobal: 23.73, status: "disponivel" },
      { box: "114", vagas: 1, areaPriv: 19.44, areaGlobal: 24.59, status: "disponivel" },
      { box: "115", vagas: 1, areaPriv: 19.44, areaGlobal: 24.59, status: "disponivel" },
      { box: "116", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "vendido", apto: "1801" },
      { box: "117", vagas: 1, areaPriv: 22.88, areaGlobal: 28.94, status: "vendido", apto: "1801" },
      { box: "118", vagas: 1, areaPriv: 20.0, areaGlobal: 25.3, status: "vendido", apto: "1801" },
      { box: "119", vagas: 1, areaPriv: 20.1, areaGlobal: 25.43, status: "vendido", apto: "1801" },
      { box: "201", vagas: 1, areaPriv: 17.98, areaGlobal: 22.74, status: "disponivel" },
      { box: "202", vagas: 1, areaPriv: 17.98, areaGlobal: 22.74, status: "disponivel" },
      { box: "203", vagas: 2, areaPriv: 41.13, areaGlobal: 52.03, status: "disponivel" },
      { box: "204", vagas: 2, areaPriv: 48.12, areaGlobal: 62.91, status: "disponivel" },
      { box: "205", vagas: 1, areaPriv: 16.94, areaGlobal: 21.43, status: "disponivel" },
      { box: "206", vagas: 1, areaPriv: 18.58, areaGlobal: 23.5, status: "disponivel" },
      { box: "207", vagas: 1, areaPriv: 20.14, areaGlobal: 25.48, status: "disponivel" },
      { box: "208", vagas: 1, areaPriv: 21.76, areaGlobal: 27.52, status: "disponivel" },
      { box: "209", vagas: 2, areaPriv: 35.14, areaGlobal: 44.45, status: "disponivel" },
      { box: "210", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "211", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "212", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "213", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "214", vagas: 1, areaPriv: 19.44, areaGlobal: 24.59, status: "disponivel" },
      { box: "215", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "216", vagas: 1, areaPriv: 22.88, areaGlobal: 28.94, status: "disponivel" },
      { box: "217", vagas: 1, areaPriv: 20.0, areaGlobal: 25.3, status: "disponivel" },
      { box: "218", vagas: 1, areaPriv: 20.1, areaGlobal: 25.43, status: "disponivel" },
      { box: "301", vagas: 2, areaPriv: 26.89, areaGlobal: 34.01, status: "disponivel" },
      { box: "302", vagas: 1, areaPriv: 17.47, areaGlobal: 22.1, status: "disponivel" },
      { box: "303", vagas: 1, areaPriv: 17.47, areaGlobal: 22.1, status: "disponivel" },
      { box: "304", vagas: 1, areaPriv: 18.15, areaGlobal: 22.96, status: "disponivel" },
      { box: "305", vagas: 1, areaPriv: 18.15, areaGlobal: 22.96, status: "disponivel" },
      { box: "306", vagas: 1, areaPriv: 14.85, areaGlobal: 18.78, status: "disponivel" },
      { box: "307", vagas: 1, areaPriv: 18.15, areaGlobal: 22.96, status: "disponivel" },
      { box: "308", vagas: 1, areaPriv: 18.15, areaGlobal: 22.96, status: "disponivel" },
      { box: "309", vagas: 1, areaPriv: 17.47, areaGlobal: 22.1, status: "disponivel" },
      { box: "310", vagas: 1, areaPriv: 17.47, areaGlobal: 22.1, status: "disponivel" },
      { box: "311", vagas: 1, areaPriv: 16.5, areaGlobal: 20.87, status: "disponivel" },
      { box: "312", vagas: 1, areaPriv: 19.29, areaGlobal: 24.4, status: "disponivel" },
      { box: "313", vagas: 2, areaPriv: 39.94, areaGlobal: 50.52, status: "disponivel" },
      { box: "314", vagas: 2, areaPriv: 49.62, areaGlobal: 65.98, status: "disponivel" },
      { box: "315", vagas: 2, areaPriv: 33.74, areaGlobal: 42.68, status: "disponivel" },
      { box: "316", vagas: 2, areaPriv: 32.05, areaGlobal: 40.54, status: "disponivel" },
      { box: "317", vagas: 1, areaPriv: 17.71, areaGlobal: 22.4, status: "disponivel" },
      { box: "318", vagas: 1, areaPriv: 17.71, areaGlobal: 22.4, status: "disponivel" },
      { box: "319", vagas: 2, areaPriv: 41.13, areaGlobal: 52.03, status: "disponivel" },
      { box: "320", vagas: 2, areaPriv: 48.36, areaGlobal: 63.27, status: "disponivel" },
      { box: "321", vagas: 1, areaPriv: 16.93, areaGlobal: 21.41, status: "disponivel" },
      { box: "322", vagas: 2, areaPriv: 34.99, areaGlobal: 44.26, status: "disponivel" },
      { box: "323", vagas: 1, areaPriv: 20.15, areaGlobal: 25.49, status: "disponivel" },
      { box: "324", vagas: 1, areaPriv: 21.78, areaGlobal: 27.55, status: "disponivel" },
      { box: "325", vagas: 2, areaPriv: 35.14, areaGlobal: 44.45, status: "disponivel" },
      { box: "326", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "327", vagas: 1, areaPriv: 18.26, areaGlobal: 23.1, status: "disponivel" },
      { box: "328", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "329", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "330", vagas: 1, areaPriv: 19.44, areaGlobal: 24.59, status: "disponivel" },
      { box: "331", vagas: 1, areaPriv: 23.1, areaGlobal: 29.22, status: "disponivel" },
      { box: "332", vagas: 1, areaPriv: 22.88, areaGlobal: 28.94, status: "disponivel" },
      { box: "333", vagas: 1, areaPriv: 20.0, areaGlobal: 25.3, status: "disponivel" },
      { box: "334", vagas: 1, areaPriv: 20.1, areaGlobal: 25.43, status: "disponivel" },
    ],
  },

  {
    id: "evolutti",
    nome: "Evolutti",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Entrega em 2028",
    entrega: "Entrega em 2028",
    ri: ["RI nº 11-47.935"],
    // Cada 3 suites leva 2 vagas — um box duplo. Como so ha 3 duplos livres
    // para 4 apartamentos, o painel manda o quarto sair com 2 box simples,
    // que e a conta que o dono ja faz. Os de 2 dormitorios levam 1 simples.
    // A ordem importa: quem vem primeiro fica com os duplos.
    vagasPorTipologia: {
      "3 dormitórios (3 suítes)": { duplo: 1 },
      // Os dois do 9o pavimento ja foram vendidos, entao esta linha nao muda a
      // conferencia de hoje — ela existe para o painel saber o que a unidade
      // leva, que e o que o proprio grupo diz em "garagem: 01 box duplo".
      "9º pavimento": { duplo: 1 },
      "2 dormitórios (1 suíte)": { simples: 1 },
      "2 dormitórios (2 suítes)": { simples: 1 },
    },
    hero: "assets/evo-hero.webp",
    folder: "assets/folder-evolutti.pdf",
    video: "",
    destaque: true,
    tagline: "O mundo evoluiu — e no Evolutti não será diferente.",
    localizacao: "Carazinho/RS — edifício de esquina com posição solar privilegiada.",
    diferenciais: [
      { titulo: "Energia renovável", desc: "Placas solares para geração de energia no consumo do condomínio." },
      { titulo: "Veículos elétricos", desc: "Suporte para carregamento de carros elétricos." },
      { titulo: "Comodidade", desc: "Persianas elétricas em todos os dormitórios, com acionamento por controle remoto." },
      { titulo: "Segurança", desc: "Fechaduras eletrônicas com biometria — nunca mais esqueça as chaves." },
      { titulo: "Lazer", desc: "Salão de festas, área fitness e bicicletário." },
      { titulo: "Estrutura", desc: "Moderno hall de entrada e posição solar privilegiada de edifício de esquina." },
    ],
    galeria: [
      { src: "assets/evo-1.webp", legenda: "Fachada — entardecer" },
      { src: "assets/evo-4.webp", legenda: "Living integrado" },
      { src: "assets/evo-5.webp", legenda: "Sala de estar" },
      { src: "assets/evo-6.webp", legenda: "Sala de jantar e cozinha" },
      { src: "assets/evo-7.webp", legenda: "Cozinha" },
      { src: "assets/evo-8.webp", legenda: "Living com sacada" },
      { src: "assets/evo-9.webp", legenda: "Suíte" },
      { src: "assets/evo-10.webp", legenda: "Suíte master" },
      { src: "assets/evo-11.webp", legenda: "Dormitório" },
      { src: "assets/evo-2.webp", legenda: "Vista aérea" },
      { src: "assets/evo-3.webp", legenda: "Andamento da obra" },
      { src: "assets/evo-p2.webp", legenda: "Planta — 2 dormitórios (1 ou 2 suítes)" },
      { src: "assets/evo-p3.webp", legenda: "Planta — 3 dormitórios (3 suítes)" },
    ],
    grupos: [
      {
        // Lojas do terreo, as tres vendidas. Cada uma tem a sua metragem, por
        // isso a area vai na propria unidade e nao no grupo.
        tipo: "Lojas",
        unidades: [
          { apto: "Loja 101", status: "vendido", areaUnit: "148 m² global · 108 m² privativo" },
          { apto: "Loja 102", status: "vendido", areaUnit: "120 m² global · 88 m² privativo" },
          { apto: "Loja 103", status: "vendido", areaUnit: "185 m² global · 135 m² privativo" },
        ],
      },
      {
        tipo: "2 dormitórios (1 suíte)",
        planta: "evo-p2",
        area: "99 m² global · 73 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "404", preco: 730000, status: "disponivel", tags: ["Casa Suspensa"], areaUnit: "135 m² global · 104 m² privativo" },
          { apto: "504", preco: 690000, status: "disponivel" },
          { apto: "604", preco: 700000, status: "disponivel" },
          { apto: "704", preco: 710000, status: "disponivel" },
          { apto: "804", preco: 720000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 dormitórios (1 suíte)",
        planta: "evo-p2",
        area: "99 m² global · 73 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "403", status: "vendido", tags: ["Casa Suspensa"], areaUnit: "149 m² global · 116 m² privativo" },
          { apto: "503", preco: 740000, status: "disponivel" },
          { apto: "603", status: "vendido" },
          { apto: "703", preco: 760000, status: "disponivel" },
          { apto: "803", preco: 770000, status: "disponivel" },
        ],
      },
      {
        tipo: "2 dormitórios (2 suítes)",
        planta: "evo-p2",
        area: "118 m² global · 87 m² privativo",
        garagem: "01 box",
        unidades: [
          { apto: "401", status: "vendido", tags: ["Casa Suspensa"], areaUnit: "215 m² global · 169 m² privativo" },
          { apto: "402", preco: 850000, status: "disponivel", tags: ["Casa Suspensa"], areaUnit: "173 m² global · 133 m² privativo" },
          { apto: "501", status: "vendido" },
          { apto: "502", preco: 800000, status: "disponivel" },
          { apto: "601", status: "vendido" },
          { apto: "602", status: "vendido" },
          { apto: "701", status: "vendido" },
          { apto: "702", status: "vendido" },
          { apto: "801", status: "vendido" },
          { apto: "802", status: "vendido" },
        ],
      },
      {
        // 9o pavimento: os dois maiores apartamentos do predio, ja vendidos.
        // Vendido nao leva numero de dormitorios — a planta costuma ser
        // modificada pelo comprador. Como nenhum esta disponivel, o grupo nao
        // aparece no site.
        tipo: "9º pavimento",
        planta: "evo-p3",
        area: "217 m² global · 164 m² privativo",
        garagem: "01 box duplo",
        unidades: [
          { apto: "901", status: "vendido" },
          { apto: "902", status: "vendido" },
        ],
      },
      {
        tipo: "3 dormitórios (3 suítes)",
        planta: "evo-p3",
        area: "179 m² global · 132 m² privativo",
        garagem: "01 box duplo",
        unidades: [
          { apto: "1001", status: "vendido" },
          { apto: "1002", preco: 1120000, status: "disponivel" },
          { apto: "1101", status: "vendido" },
          { apto: "1102", preco: 1130000, status: "disponivel" },
          { apto: "1201", status: "vendido" },
          { apto: "1202", preco: 1140000, status: "disponivel" },
          { apto: "1301", status: "vendido" },
          { apto: "1302", preco: 1150000, status: "disponivel" },
        ],
      },
    ],
    // Box de garagem avulsos. Nao aparecem no site publico (app.js so le
    // grupos/terrenos/outros) — sao usados apenas pelo painel administrativo.
    boxes: [
      { box: "201", vagas: 1, areaPriv: 16.43, areaGlobal: 19.45, status: "vendido" },
      { box: "202", vagas: 1, areaPriv: 18.36, areaGlobal: 21.74, status: "vendido" },
      { box: "203", vagas: 1, areaPriv: 13.85, areaGlobal: 16.4, status: "vendido" },
      { box: "204", vagas: 1, areaPriv: 13.85, areaGlobal: 16.4, status: "vendido" },
      { box: "205", vagas: 1, areaPriv: 14.71, areaGlobal: 17.41, status: "vendido" },
      { box: "206", vagas: 1, areaPriv: 15.19, areaGlobal: 17.98, status: "disponivel" },
      { box: "207", vagas: 1, areaPriv: 14.38, areaGlobal: 17.02, status: "vendido" },
      { box: "208", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "209", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "210", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "211", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "212", vagas: 1, areaPriv: 13.26, areaGlobal: 15.7, status: "disponivel", obs: "Voltou" },
      { box: "213", vagas: 1, areaPriv: 13.26, areaGlobal: 15.7, status: "vendido" },
      { box: "214", vagas: 1, areaPriv: 13.3, areaGlobal: 15.74, status: "vendido" },
      { box: "215", vagas: 1, areaPriv: 14.34, areaGlobal: 16.98, status: "vendido" },
      { box: "216", vagas: 2, areaPriv: 36.28, areaGlobal: 42.96, status: "vendido" },
      { box: "217", vagas: 2, areaPriv: 29.26, areaGlobal: 34.64, status: "disponivel" },
      { box: "301", vagas: 1, areaPriv: 16.43, areaGlobal: 19.45, status: "vendido" },
      { box: "302", vagas: 1, areaPriv: 18.36, areaGlobal: 21.74, status: "vendido" },
      { box: "303", vagas: 1, areaPriv: 13.85, areaGlobal: 16.4, status: "disponivel" },
      { box: "304", vagas: 1, areaPriv: 13.85, areaGlobal: 16.4, status: "disponivel" },
      { box: "305", vagas: 1, areaPriv: 14.71, areaGlobal: 17.41, status: "disponivel" },
      { box: "306", vagas: 1, areaPriv: 15.19, areaGlobal: 17.98, status: "disponivel" },
      { box: "307", vagas: 1, areaPriv: 14.38, areaGlobal: 17.02, status: "vendido" },
      { box: "308", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "309", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "vendido" },
      { box: "310", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "disponivel" },
      { box: "311", vagas: 1, areaPriv: 13.61, areaGlobal: 16.11, status: "disponivel" },
      { box: "312", vagas: 1, areaPriv: 13.26, areaGlobal: 15.7, status: "disponivel" },
      { box: "313", vagas: 1, areaPriv: 13.26, areaGlobal: 15.7, status: "disponivel" },
      { box: "314", vagas: 1, areaPriv: 13.3, areaGlobal: 15.74, status: "disponivel" },
      { box: "315", vagas: 1, areaPriv: 14.34, areaGlobal: 16.98, status: "disponivel" },
      { box: "316", vagas: 2, areaPriv: 36.28, areaGlobal: 42.96, status: "vendido" },
      { box: "317", vagas: 2, areaPriv: 27.84, areaGlobal: 32.96, status: "disponivel" },
      { box: "318", vagas: 2, areaPriv: 27.84, areaGlobal: 32.96, status: "vendido" },
      { box: "319", vagas: 2, areaPriv: 31.98, areaGlobal: 37.86, status: "disponivel" },
    ],
  },

  {
    id: "premium-office",
    nome: "Premium Office",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "comercial",
    status: "obra",
    statusLabel: "Entrega em 2029",
    entrega: "Entrega em 2029",
    ri: ["RI nº 1-50.267"],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "Sala térreo": { simples: 3 },
      "Sala 2º pavimento": { simples: 1 },
      "Sala 115 m²": { simples: 1 },
      "Sala 122 a 129 m²": { simples: 1 },
      "Sala 54 m²": { simples: 1 },
      "Sala 72 m²": { simples: 1 },
      "Sala 76 m²": { simples: 1 },
    },
    hero: "assets/po-render-3.webp",
    folder: "",
    video: "",
    destaque: true,
    tagline: "Não é só um moderno centro clínico — é o futuro da área da saúde de Carazinho.",
    localizacao: "Rua Cipriano da Luz — em frente à Praça do Hospital de Clínicas de Carazinho.",
    diferenciais: [
      { titulo: "Rooftop", desc: "Conforto e vista privilegiada que transformam a espera do paciente em uma experiência única." },
      { titulo: "Sunset Lounge", desc: "Espaço privativo dos profissionais, para relaxar e recarregar entre atendimentos." },
      { titulo: "Elevador para maca", desc: "Dois elevadores, sendo um deles preparado para maca." },
      { titulo: "Hall imponente", desc: "Pé direito duplo, com acesso para veículos e ambulâncias na entrada." },
      { titulo: "Personalização", desc: "Possibilidade de unir salas, ajustando o tamanho à sua necessidade." },
      { titulo: "Box de garagem", desc: "Todas as salas com box de garagem." },
      { titulo: "WCs sociais acessíveis", desc: "Banheiros sociais com acessibilidade em todos os pavimentos." },
      { titulo: "Design em LED", desc: "Linhas iluminadas que destacam o edifício à noite." },
    ],
    galeria: [
      { src: "assets/po-render-1.webp", legenda: "Fachada — vista diurna" },
      { src: "assets/po-render-2.webp", legenda: "Fachada — entardecer" },
      { src: "assets/po-obra1.webp", legenda: "Fachada completa" },
      { src: "assets/po-garagem.webp", legenda: "Volumetria do edifício" },
      { src: "assets/po-hall.webp", legenda: "Hall de entrada — pé direito duplo" },
      { src: "assets/po-int1.webp", legenda: "Hall — pé direito duplo" },
      { src: "assets/po-int2.webp", legenda: "Recepção Premium Office" },
      { src: "assets/po-r4.webp", legenda: "Escritório / consultório — projeto" },
      { src: "assets/po-r5.webp", legenda: "Escritório / consultório — projeto" },
      { src: "assets/po-r6.webp", legenda: "Sala com divisórias de vidro" },
      { src: "assets/po-rooftop.webp", legenda: "Rooftop" },
      { src: "assets/po-lounge.webp", legenda: "Sunset Lounge" },
      { src: "assets/po-obra2.webp", legenda: "Terraço / rooftop" },
      { src: "assets/po-vaga.webp", legenda: "Garagem coberta" },
      { src: "assets/po-aerial.webp", legenda: "Vista aérea" },
      { src: "assets/po-aerial2.webp", legenda: "Vista aérea — bairro" },
      { src: "assets/po-loc.webp", legenda: "Localização — em frente à Praça do Hospital de Clínicas" },
      // Do 3o ao 8o o pavimento e o mesmo, entao esta planta vale para os seis
      // andares — o desenho e o do 3o, e os finais 01 a 05 se repetem acima.
      { src: "assets/po-planta-tipo.webp", legenda: "Planta baixa — pavimento tipo, 3º ao 8º (finais 01 a 05)", tecnica: true },
      // O 2o pavimento tem divisao propria: tres salas maiores, no lugar das
      // cinco dos andares de cima. Sao plantas de obra, nao humanizadas — por
      // isso a marca "tecnica", que as poe sob o titulo certo no visor.
      { src: "assets/po-planta-2pav.webp", legenda: "Planta baixa — 2º pavimento (salas 201 a 203)", tecnica: true },
      { src: "assets/po-map.webp", legenda: "Mapa — Rua Cipriano da Luz" },
    ],
    grupos: [
      {
        tipo: "Sala comercial no térreo",
        area: "387 m² global · 219 m² privativo",
        garagem: "03 vagas de garagem",
        estoque: "Sala térreo",
        unidades: [{ apto: "101", status: "vendido" }],
      },
      {
        tipo: "Salas comerciais",
        area: "Áreas variadas",
        garagem: "01 vaga de garagem por sala",
        estoque: "Sala 2º pavimento",
        planta: "po-planta-2pav",
        unidades: [
          { apto: "201", preco: 1140000, status: "disponivel", areaUnit: "160 m² global · 90 m² privativo" },
          { apto: "202", preco: 1010000, status: "disponivel", areaUnit: "139 m² global · 78 m² privativo" },
          { apto: "203", preco: 660000, status: "disponivel", areaUnit: "88 m² global · 49 m² privativo" },
        ],
      },
      // Do 3o ao 8o pavimento a planta e a mesma: cinco salas, finais 01 a 05,
      // e cada tipologia e uma sala dela (po-planta-tipo). So o 2o pavimento
      // tem divisao propria — tres salas maiores — e o terreo (sala 101,
      // vendida) segue sem planta, que o painel cobra.
      {
        tipo: "Sala comercial",
        area: "115 m² global · 65 m² privativo",
        garagem: "01 vaga de garagem",
        estoque: "Sala 115 m²",
        planta: "po-planta-tipo",
        unidades: [
          { apto: "301", status: "vendido" },
          { apto: "401", status: "vendido" },
          { apto: "501", status: "vendido" },
          { apto: "601", status: "vendido" },
          { apto: "701", status: "vendido" },
          { apto: "801", preco: 850000, status: "disponivel" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "129 m² global · 73 m² privativo",
        garagem: "01 vaga de garagem",
        estoque: "Sala 122 a 129 m²",
        planta: "po-planta-tipo",
        unidades: [{ apto: "802", preco: 880000, status: "disponivel" }],
      },
      // As outras salas de final 02 tem cada uma a sua area; contam junto com a
      // 802 no estoque do painel e ja estao todas vendidas.
      {
        tipo: "Sala comercial",
        area: "Áreas variadas",
        garagem: "01 vaga de garagem",
        estoque: "Sala 122 a 129 m²",
        planta: "po-planta-tipo",
        unidades: [
          { apto: "302", status: "vendido", areaUnit: "122 m² global · 69 m² privativo" },
          { apto: "402", status: "vendido", areaUnit: "124 m² global · 70 m² privativo" },
          { apto: "502", status: "vendido", areaUnit: "125 m² global · 70 m² privativo" },
          { apto: "602", status: "vendido", areaUnit: "126 m² global · 71 m² privativo" },
          { apto: "702", status: "vendido", areaUnit: "128 m² global · 72 m² privativo" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "54 m² global · 31 m² privativo",
        garagem: "01 vaga de garagem",
        estoque: "Sala 54 m²",
        planta: "po-planta-tipo",
        unidades: [
          { apto: "303", status: "vendido" },
          { apto: "403", status: "vendido" },
          { apto: "503", status: "vendido" },
          { apto: "603", status: "vendido" },
          { apto: "703", status: "vendido" },
          { apto: "803", preco: 480000, status: "disponivel" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "72 m² global · 40 m² privativo",
        garagem: "01 vaga de garagem",
        estoque: "Sala 72 m²",
        planta: "po-planta-tipo",
        unidades: [
          { apto: "304", preco: 560000, status: "disponivel" },
          { apto: "404", status: "vendido" },
          { apto: "504", status: "vendido" },
          { apto: "604", status: "vendido" },
          { apto: "704", status: "vendido" },
          { apto: "804", preco: 600000, status: "disponivel" },
        ],
      },
      {
        tipo: "Sala comercial",
        area: "76 m² global · 43 m² privativo",
        garagem: "01 vaga de garagem",
        estoque: "Sala 76 m²",
        planta: "po-planta-tipo",
        unidades: [
          { apto: "305", status: "vendido" },
          { apto: "405", status: "vendido" },
          { apto: "505", status: "vendido" },
          { apto: "605", status: "vendido" },
          { apto: "705", preco: 600000, status: "disponivel" },
          { apto: "805", status: "vendido" },
        ],
      },
    ],
    // Box de garagem do subsolo (01 a 27) e do terreo (101 a 113). Nao aparecem
    // no site publico (app.js so le grupos/terrenos/outros) — sao usados apenas
    // pelo painel administrativo, que confere se as vagas fecham.
    boxes: [
      { box: "01", vagas: 1, areaPriv: 14.3, areaGlobal: 19.81, status: "vendido", apto: "805" },
      { box: "02", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "305" },
      { box: "03", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "505" },
      { box: "04", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "405" },
      { box: "05", vagas: 1, areaPriv: 16.24, areaGlobal: 22.51, status: "vendido", apto: "703" },
      { box: "06", vagas: 1, areaPriv: 15.94, areaGlobal: 22.09, status: "vendido", apto: "605" },
      { box: "07", vagas: 1, areaPriv: 13.26, areaGlobal: 18.37, status: "disponivel" },
      { box: "08", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "301" },
      { box: "09", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "303" },
      { box: "10", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "403" },
      { box: "11", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "501" },
      { box: "12", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "604" },
      { box: "13", vagas: 1, areaPriv: 14.56, areaGlobal: 20.17, status: "disponivel" },
      { box: "14", vagas: 1, areaPriv: 15.34, areaGlobal: 21.26, status: "vendido", apto: "601" },
      // Vaga PNE: existe no predio, mas nao se vende nem se usa. O painel a
      // deixa fora da conta de garagem.
      { box: "15", vagas: 1, status: "disponivel", pne: true, obs: "Vaga PNE" },
      { box: "16", vagas: 1, areaPriv: 13.78, areaGlobal: 19.1, status: "vendido", apto: "602" },
      { box: "17", vagas: 1, areaPriv: 15.6, areaGlobal: 21.61, status: "vendido", apto: "503" },
      { box: "18", vagas: 1, areaPriv: 15.08, areaGlobal: 20.9, status: "vendido", apto: "704" },
      { box: "19", vagas: 1, areaPriv: 14.04, areaGlobal: 19.45, status: "vendido", apto: "404" },
      { box: "20", vagas: 1, areaPriv: 14.56, areaGlobal: 20.17, status: "vendido", apto: "401" },
      { box: "21", vagas: 1, areaPriv: 13.0, areaGlobal: 18.01, status: "vendido", apto: "402" },
      { box: "22", vagas: 1, areaPriv: 15.6, areaGlobal: 21.61, status: "vendido", apto: "101" },
      { box: "23", vagas: 1, areaPriv: 15.6, areaGlobal: 21.61, status: "vendido", apto: "101" },
      { box: "24", vagas: 1, areaPriv: 14.3, areaGlobal: 19.81, status: "vendido", apto: "101" },
      { box: "25", vagas: 1, areaPriv: 13.0, areaGlobal: 18.01, status: "vendido", apto: "302" },
      { box: "26", vagas: 1, areaPriv: 13.0, areaGlobal: 18.01, status: "vendido", apto: "502" },
      { box: "27", vagas: 1, areaPriv: 12.74, areaGlobal: 17.65, status: "vendido", apto: "603" },
      { box: "101", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "102", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "103", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "104", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "105", vagas: 1, areaPriv: 16.24, areaGlobal: 22.51, status: "disponivel" },
      { box: "106", vagas: 1, areaPriv: 15.94, areaGlobal: 22.09, status: "disponivel" },
      { box: "107", vagas: 1, areaPriv: 13.26, areaGlobal: 18.37, status: "disponivel" },
      { box: "108", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "109", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "disponivel" },
      { box: "110", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "701", obs: "Permuta" },
      { box: "111", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "702", obs: "Permuta" },
      { box: "112", vagas: 1, areaPriv: 13.52, areaGlobal: 18.74, status: "vendido", apto: "504", obs: "Permuta" },
      { box: "113", vagas: 1, areaPriv: 14.56, areaGlobal: 20.17, status: "disponivel" },
    ],
  },

  {
    id: "boulevard",
    nome: "Boulevard Residence",
    confirmado: true,
    cidade: "Ibirubá/RS",
    categoria: "residencial",
    status: "obra",
    statusLabel: "Entrega em 2028",
    entrega: "Entrega em 2028",
    ri: ["RI nº 1-50.267"],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "3 suítes + lavabo": { duplo: 1 },
      "2 suítes + lavabo": { simples: 1 },
      "2 dormitórios (1 suíte)": { simples: 1 },
    },
    hero: "assets/bv-hero.webp",
    folder: "",
    video: "",
    destaque: true,
    tagline: "Onde morar é sinônimo de bem-estar.",
    localizacao: "Rua Getúlio Vargas — em frente à Praça Gen. Osório, Ibirubá/RS.",
    diferenciais: [
      { titulo: "Localização privilegiada", desc: "No coração de Ibirubá, em frente à Praça Gen. Osório, com fácil acesso a comércio, serviços e lazer." },
      { titulo: "Qualidade e bem-estar", desc: "Acabamentos de alto padrão e ambientes integrados, pensados para conforto, segurança e praticidade." },
      { titulo: "Lazer completo", desc: "Piscina, estar de fogo, espaço fitness, playground, espaço pub com churrasqueira e jogos, salão de festas + espaço kids." },
    ],
    galeria: [
      { src: "assets/bv-1.webp", legenda: "Fachada" },
      { src: "assets/bv-2.webp", legenda: "Área de lazer" },
      { src: "assets/bv-3.webp", legenda: "Piscina" },
      { src: "assets/bv-4.webp", legenda: "Ambientes" },
      { src: "assets/bv-9.webp", legenda: "Lazer" },
      { src: "assets/bv-5.webp", legenda: "Ambientes" },
      { src: "assets/bv-6.webp", legenda: "Espaço pub" },
      { src: "assets/bv-7.webp", legenda: "Salão de festas" },
      { src: "assets/bv-8.webp", legenda: "Espaço kids" },
      { src: "assets/bv-planta.webp", legenda: "Planta — pavimento" },
      { src: "assets/bv-planta-lazer.webp", legenda: "Planta — área de lazer" },
      { src: "assets/bv-folder.webp", legenda: "Folder do empreendimento" },
      { src: "assets/bv-map.webp", legenda: "Rua Getúlio Vargas — frente à Praça Gen. Osório" },
    ],
    grupos: [
      {
        tipo: "3 suítes + lavabo",
        area: "212 m² global · 149 m² privativo",
        garagem: "Box duplo",
        unidades: [
          { apto: "301", status: "vendido" },
          { apto: "401", status: "vendido" },
          { apto: "501", preco: 1420000, status: "disponivel" },
          { apto: "601", status: "vendido" },
          { apto: "701", status: "vendido" },
          { apto: "801", preco: 1440000, status: "disponivel" },
          { apto: "901", preco: 1460000, status: "disponivel" },
          { apto: "1001", status: "vendido" },
          { apto: "1101", status: "vendido" },
          { apto: "1201", status: "vendido" },
          { apto: "1301", status: "vendido" },
        ],
      },
      {
        tipo: "3 suítes + lavabo",
        area: "212 m² global · 149 m² privativo",
        garagem: "Box duplo",
        unidades: [
          { apto: "302", status: "vendido" },
          { apto: "402", status: "vendido" },
          { apto: "502", status: "vendido" },
          { apto: "602", preco: 1440000, status: "disponivel" },
          { apto: "702", preco: 1460000, status: "disponivel" },
          { apto: "802", status: "vendido" },
          { apto: "902", preco: 1480000, status: "disponivel" },
          { apto: "1002", preco: 1500000, status: "disponivel" },
          { apto: "1102", preco: 1520000, status: "disponivel" },
          { apto: "1202", status: "vendido" },
          { apto: "1302", status: "vendido" },
        ],
      },
      {
        tipo: "2 suítes + lavabo",
        area: "131 m² global · 93 m² privativo",
        garagem: "01 box de garagem",
        unidades: [
          { apto: "304", preco: 870000, status: "disponivel", tags: ["Casa Suspensa"], areaUnit: "165 m² global · 121 m² privativo" },
          { apto: "404", preco: 850000, status: "disponivel" },
          { apto: "504", preco: 860000, status: "disponivel" },
          { apto: "604", status: "vendido" },
          { apto: "704", preco: 880000, status: "disponivel" },
          { apto: "804", status: "vendido" },
          { apto: "904", preco: 900000, status: "disponivel" },
          { apto: "1004", status: "vendido" },
          { apto: "1104", preco: 920000, status: "disponivel" },
          { apto: "1204", preco: 930000, status: "disponivel" },
          { apto: "1304", status: "vendido" },
        ],
      },
      {
        tipo: "2 dormitórios (1 suíte)",
        area: "127 m² global · 91 m² privativo",
        garagem: "01 box",
        // Falta o 303 neste final: ele nao esta no estoque e nenhum box vendido
        // aponta para ele, entao nao da para dizer se foi vendido ou se ainda
        // esta a venda. Fica de fora ate a construtora confirmar.
        unidades: [
          { apto: "403", preco: 820000, status: "disponivel" },
          { apto: "503", preco: 830000, status: "disponivel" },
          { apto: "603", preco: 840000, status: "disponivel" },
          { apto: "703", preco: 850000, status: "disponivel" },
          { apto: "803", preco: 860000, status: "disponivel" },
          { apto: "903", preco: 870000, status: "disponivel" },
          { apto: "1003", preco: 880000, status: "disponivel" },
          { apto: "1103", preco: 890000, status: "disponivel" },
          { apto: "1203", preco: 900000, status: "disponivel" },
          { apto: "1303", status: "vendido" },
        ],
      },
    ],
    // Box do subsolo (101 a 126) e do 2o pavimento (201 a 230). Areas e vagas
    // pela Tabela de Vendas Boulevard de 31/07/2026; a ligacao de cada box com
    // o apartamento vem das plantas de box vendidos de 10/07/2025 (subsolo) e
    // 25/11/2025 (2o pavimento). As duas vagas PCD (102 e 202) nao entram na
    // tabela de vendas: a area delas e a da planta. Nao aparecem no site
    // publico — sao usados apenas pelo painel administrativo.
    boxes: [
      { box: "101", vagas: 1, areaPriv: 15.39, areaGlobal: 18.6, status: "vendido", apto: "804", obs: "Com depósito" },
      { box: "102", vagas: 1, areaPriv: 14.9, status: "disponivel", obs: "Vaga PCD", pne: true },
      { box: "103", vagas: 1, areaPriv: 13.74, areaGlobal: 16.61, status: "vendido", apto: "604" },
      { box: "104", vagas: 1, areaPriv: 13.59, areaGlobal: 16.42, status: "disponivel" },
      { box: "105", vagas: 1, areaPriv: 13.86, areaGlobal: 16.76, status: "disponivel" },
      { box: "106", vagas: 1, areaPriv: 13.48, areaGlobal: 16.29, status: "disponivel" },
      { box: "107", vagas: 1, areaPriv: 13.3, areaGlobal: 16.08, status: "disponivel" },
      { box: "108", vagas: 1, areaPriv: 13.48, areaGlobal: 16.29, status: "disponivel" },
      { box: "109", vagas: 1, areaPriv: 13.4, areaGlobal: 16.2, status: "disponivel" },
      { box: "110", vagas: 1, areaPriv: 13.38, areaGlobal: 16.17, status: "disponivel" },
      { box: "111", vagas: 1, areaPriv: 13.14, areaGlobal: 15.88, status: "disponivel" },
      { box: "112", vagas: 1, areaPriv: 14.56, areaGlobal: 17.61, status: "disponivel" },
      { box: "113", vagas: 2, areaPriv: 41.48, areaGlobal: 50.15, status: "disponivel", obs: "Com depósito" },
      { box: "114", vagas: 2, areaPriv: 32.26, areaGlobal: 38.99, status: "disponivel", obs: "Com depósito" },
      { box: "115", vagas: 2, areaPriv: 36.12, areaGlobal: 43.67, status: "vendido", apto: "302", obs: "Com depósito" },
      { box: "116", vagas: 2, areaPriv: 36.58, areaGlobal: 44.22, status: "vendido", apto: "802", obs: "Com depósito" },
      { box: "117", vagas: 2, areaPriv: 31.26, areaGlobal: 37.79, status: "disponivel", obs: "Com depósito" },
      { box: "118", vagas: 2, areaPriv: 30.81, areaGlobal: 37.25, status: "disponivel", obs: "Com depósito" },
      { box: "119", vagas: 2, areaPriv: 27.73, areaGlobal: 33.52, status: "disponivel" },
      { box: "120", vagas: 2, areaPriv: 26.97, areaGlobal: 32.6, status: "disponivel" },
      { box: "121", vagas: 2, areaPriv: 26.59, areaGlobal: 32.14, status: "disponivel" },
      { box: "122", vagas: 2, areaPriv: 26.95, areaGlobal: 32.58, status: "disponivel" },
      { box: "123", vagas: 2, areaPriv: 26.82, areaGlobal: 32.42, status: "disponivel" },
      { box: "124", vagas: 2, areaPriv: 26.76, areaGlobal: 32.35, status: "disponivel" },
      { box: "125", vagas: 2, areaPriv: 26.28, areaGlobal: 31.77, status: "disponivel" },
      { box: "126", vagas: 2, areaPriv: 29.12, areaGlobal: 35.2, status: "disponivel" },
      { box: "201", vagas: 2, areaPriv: 29.92, areaGlobal: 36.17, status: "vendido", apto: "1301", obs: "Com depósito" },
      { box: "202", vagas: 1, areaPriv: 20.64, status: "disponivel", obs: "Vaga PCD", pne: true },
      { box: "203", vagas: 1, areaPriv: 20.1, areaGlobal: 24.3, status: "disponivel" },
      { box: "204", vagas: 1, areaPriv: 15.94, areaGlobal: 19.26, status: "vendido", apto: "402" },
      { box: "205", vagas: 2, areaPriv: 26.1, areaGlobal: 31.55, status: "vendido", apto: "301", obs: "Com depósito" },
      { box: "206", vagas: 1, areaPriv: 20.46, areaGlobal: 24.73, status: "vendido", apto: "402" },
      { box: "207", vagas: 1, areaPriv: 20.98, areaGlobal: 25.36, status: "vendido", apto: "1301" },
      { box: "208", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "1201" },
      { box: "209", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "1201" },
      { box: "210", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "1303" },
      { box: "211", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "1303" },
      { box: "212", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "701" },
      { box: "213", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "701" },
      { box: "214", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "601" },
      { box: "215", vagas: 1, areaPriv: 16.03, areaGlobal: 19.37, status: "vendido", apto: "601" },
      { box: "216", vagas: 2, areaPriv: 31.76, areaGlobal: 38.4, status: "vendido", apto: "1001", obs: "Com depósito" },
      { box: "217", vagas: 2, areaPriv: 32.94, areaGlobal: 39.82, status: "vendido", apto: "1302", obs: "Com depósito" },
      { box: "218", vagas: 2, areaPriv: 39.42, areaGlobal: 47.66, status: "vendido", apto: "1302", obs: "Com depósito" },
      { box: "219", vagas: 1, areaPriv: 20.96, areaGlobal: 25.34, status: "vendido", apto: "1304", obs: "Com depósito" },
      { box: "220", vagas: 2, areaPriv: 42.54, areaGlobal: 51.43, status: "vendido", apto: "1202", obs: "Com depósito" },
      { box: "221", vagas: 2, areaPriv: 24.76, areaGlobal: 29.93, status: "disponivel" },
      { box: "222", vagas: 2, areaPriv: 31.7, areaGlobal: 38.32, status: "disponivel", obs: "Com depósito" },
      { box: "223", vagas: 2, areaPriv: 26.52, areaGlobal: 32.06, status: "vendido", apto: "1101" },
      { box: "224", vagas: 2, areaPriv: 28, areaGlobal: 33.84, status: "vendido", apto: "1101" },
      { box: "225", vagas: 2, areaPriv: 31, areaGlobal: 37.48, status: "vendido", apto: "401", obs: "Com depósito" },
      { box: "226", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "502" },
      { box: "227", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "502" },
      { box: "228", vagas: 1, areaPriv: 15.73, areaGlobal: 19.02, status: "vendido", apto: "1004" },
      { box: "229", vagas: 1, areaPriv: 16.03, areaGlobal: 19.37, status: "disponivel" },
      { box: "230", vagas: 2, areaPriv: 31.76, areaGlobal: 38.4, status: "disponivel", obs: "Com depósito" },
    ],
  },

  {
    id: "personalite",
    nome: "Personalité",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 11-38.407"],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "3 suítes + lavabo": { duplo: 1 },
    },
    hero: "assets/perso-1.webp",
    folder: "",
    video: "",
    destaque: true,
    tagline: "Alto padrão Personalité — venha morar com estilo.",
    localizacao: "Região central de Carazinho/RS — edifício de esquina com posição solar privilegiada.",
    diferenciais: [
      { titulo: "Lazer", desc: "Piscina aquecida e 2 salões de festas completos, com terraço e acesso à piscina." },
      { titulo: "Conforto", desc: "Acabamento refinado, aquecimento a gás, 2 elevadores e sacada com churrasqueira a carvão." },
      { titulo: "Alto padrão", desc: "Amplos apartamentos, hall de entrada com pé direito duplo, porcelanato e gesso em todo o apartamento." },
      { titulo: "Estrutura", desc: "Medição individual de água, luz e gás; detalhes em vidro laminado; esquadrias de alumínio anodizado." },
    ],
    galeria: [
      { src: "assets/perso-2.webp", legenda: "Hall de entrada" },
      { src: "assets/perso-4.webp", legenda: "Hall — pé direito alto" },
      { src: "assets/perso-3.webp", legenda: "Salão de festas" },
      { src: "assets/perso-5.webp", legenda: "Piscina aquecida" },
      { src: "assets/perso-7.webp", legenda: "Salão de festas com terraço" },
      { src: "assets/perso-6.webp", legenda: "Apartamento — cozinha integrada" },
      { src: "assets/perso-planta.webp", legenda: "Planta — 3 suítes + lavabo" },
      { src: "assets/perso-map.webp", legenda: "Localização — Centro" },
    ],
    grupos: [
      {
        tipo: "3 suítes + lavabo",
        planta: "perso-planta",
        area: "172 m² global · 132 m² privativo",
        garagem: "Box duplo",
        unidades: [
          { apto: "602", preco: 1310000, status: "disponivel" },
          { apto: "902", preco: 1450000, status: "disponivel", tags: ["Semimobiliado"] },
        ],
      },
    ],
    // Box do terreo (101 a 139) e do 2o pavimento (201 a 226), pelas plantas
    // de box vendidos de 06/05/2026 e 20/06/2025. Nao aparecem no site
    // publico — sao usados apenas pelo painel administrativo.
    boxes: [
      { box: "101", vagas: 1, areaPriv: 14.04, status: "vendido", apto: "1102" },
      { box: "102", vagas: 1, areaPriv: 16.87, status: "vendido", apto: "704" },
      { box: "103", vagas: 1, areaPriv: 16.86, status: "vendido", apto: "302" },
      { box: "104", vagas: 1, areaPriv: 15.33, status: "vendido", apto: "302" },
      { box: "105", vagas: 1, areaPriv: 15.06, status: "vendido", apto: "1102" },
      { box: "106", vagas: 1, areaPriv: 15.75, status: "vendido", apto: "303" },
      { box: "107", vagas: 1, areaPriv: 15.9, status: "vendido", apto: "404" },
      { box: "108", vagas: 1, areaPriv: 15.45, status: "vendido", apto: "1004" },
      { box: "109", vagas: 1, areaPriv: 15.45, status: "vendido", apto: "603" },
      { box: "110", vagas: 2, areaPriv: 28.97, status: "vendido", apto: "403" },
      { box: "111", vagas: 2, areaPriv: 25.02, status: "disponivel" },
      { box: "112", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "903" },
      { box: "113", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "1202" },
      { box: "114", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "1204" },
      { box: "115", vagas: 2, areaPriv: 25.58, status: "vendido", apto: "904" },
      { box: "116", vagas: 2, areaPriv: 34.73, status: "vendido", apto: "1302" },
      { box: "117", vagas: 1, areaPriv: 12, status: "vendido", apto: "402" },
      { box: "118", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "604" },
      { box: "119", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "1201" },
      { box: "120", vagas: 1, areaPriv: 12, status: "vendido", apto: "801" },
      { box: "121", vagas: 1, areaPriv: 13, status: "vendido", apto: "1003" },
      { box: "122", vagas: 1, areaPriv: 13, status: "vendido", apto: "1104" },
      { box: "123", vagas: 1, areaPriv: 13.25, status: "vendido", apto: "301" },
      { box: "124", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "301" },
      { box: "125", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "703" },
      { box: "126", vagas: 2, areaPriv: 24.99, status: "vendido", apto: "401" },
      { box: "127", vagas: 1, areaPriv: 13, status: "vendido", apto: "402" },
      { box: "128", vagas: 1, areaPriv: 13, status: "vendido", apto: "1003" },
      { box: "129", vagas: 1, areaPriv: 13.78, status: "vendido", apto: "502" },
      { box: "130", vagas: 1, areaPriv: 13.52, status: "disponivel" },
      { box: "131", vagas: 1, areaPriv: 13, status: "vendido", apto: "1002" },
      { box: "132", vagas: 1, areaPriv: 12, status: "vendido", apto: "1103" },
      { box: "133", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "1103" },
      { box: "134", vagas: 1, areaPriv: 17.47, status: "disponivel" },
      { box: "135", vagas: 2, areaPriv: 32.41, status: "vendido", apto: "Sala 101" },
      { box: "136", vagas: 2, areaPriv: 25, status: "disponivel" },
      { box: "137", vagas: 2, areaPriv: 25, status: "vendido", apto: "803" },
      { box: "138", vagas: 2, areaPriv: 26, status: "vendido", apto: "1201" },
      { box: "139", vagas: 2, areaPriv: 25, status: "vendido", apto: "802" },
      { box: "201", vagas: 1, areaPriv: 14.04, status: "vendido", apto: "503" },
      { box: "202", vagas: 1, areaPriv: 16.87, status: "vendido", apto: "503" },
      { box: "203", vagas: 1, areaPriv: 16.86, status: "vendido", apto: "503" },
      { box: "204", vagas: 1, areaPriv: 15.33, status: "vendido", apto: "1302" },
      { box: "205", vagas: 1, areaPriv: 15.06, status: "vendido", apto: "504" },
      { box: "206", vagas: 1, areaPriv: 15.75, status: "vendido", apto: "804" },
      { box: "207", vagas: 1, areaPriv: 15.9, status: "vendido", apto: "Sala 207" },
      { box: "208", vagas: 1, areaPriv: 15.45, status: "vendido", apto: "Sala 207" },
      { box: "209", vagas: 1, areaPriv: 15.45, status: "vendido", apto: "Sala 207" },
      { box: "210", vagas: 2, areaPriv: 28.97, status: "vendido", apto: "501" },
      { box: "211", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "601" },
      { box: "212", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "1304" },
      { box: "213", vagas: 2, areaPriv: 25.02, status: "disponivel" },
      { box: "214", vagas: 2, areaPriv: 25.02, status: "vendido", apto: "301" },
      { box: "215", vagas: 2, areaPriv: 25.58, status: "vendido", apto: "801" },
      { box: "216", vagas: 2, areaPriv: 34.73, status: "vendido", apto: "701" },
      { box: "217", vagas: 1, areaPriv: 17.94, status: "vendido", apto: "1301" },
      { box: "218", vagas: 1, areaPriv: 14.98, status: "vendido", apto: "1101" },
      { box: "219", vagas: 2, areaPriv: 25, status: "vendido", apto: "702" },
      { box: "220", vagas: 2, areaPriv: 25, status: "vendido", apto: "1101" },
      { box: "221", vagas: 2, areaPriv: 25, status: "vendido", apto: "502" },
      { box: "222", vagas: 2, areaPriv: 24, status: "vendido", apto: "Sala 101" },
      { box: "223", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "901" },
      { box: "224", vagas: 2, areaPriv: 27.5, status: "vendido", apto: "1002" },
      { box: "225", vagas: 2, areaPriv: 27, status: "vendido", apto: "1001" },
      { box: "226", vagas: 2, areaPriv: 24, status: "vendido", apto: "1001" },
    ],
  },

  {
    id: "prime",
    nome: "Prime",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 2-45.162"],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "3 dormitórios (2 suítes)": { duplo: 1 },
    },
    hero: "assets/prime-hero.webp",
    folder: "",
    video: "",
    destaque: true,
    tagline: "Prime, no coração da cidade — qualidade de vida todos os dias.",
    localizacao: "R. Venâncio Aires, 121 — Centro, Carazinho/RS.",
    diferenciais: [
      { titulo: "Localização", desc: "Edifício de esquina com posição solar privilegiada, ao lado de mercado, escolas, farmácia e tudo mais necessário no dia a dia." },
      { titulo: "Alto padrão", desc: "Living integrado com churrasqueira a carvão e vista para a praça central." },
      { titulo: "Lazer e convivência", desc: "Salão de festas com terraço e hall de entrada com pé direito duplo." },
      { titulo: "Conforto", desc: "Acabamento refinado, aquecimento a gás, 2 elevadores, persianas elétricas e fechadura biométrica." },
    ],
    galeria: [
      { src: "assets/prime-4.webp", legenda: "Fachada — edifício de esquina" },
      { src: "assets/prime-1.webp", legenda: "Apartamento decorado — living" },
      { src: "assets/prime-2.webp", legenda: "Apartamento decorado — estar" },
      { src: "assets/prime-3.webp", legenda: "Apartamento decorado — suíte" },
      { src: "assets/prime-6.webp", legenda: "Hall de entrada" },
      { src: "assets/prime-5.webp", legenda: "Fechadura biométrica" },
      { src: "assets/prime-planta.webp", legenda: "Planta — 3 dormitórios (2 suítes)" },
    ],
    grupos: [
      {
        tipo: "3 dormitórios (2 suítes)",
        planta: "prime-planta",
        area: "124 m² global · 96 m² privativo",
        garagem: "Box duplo",
        unidades: [{ apto: "303", preco: 1180000, status: "disponivel", tags: ["Decorado"] }],
      },
    ],
    // Box de garagem do terreo (101 a 118) e do subsolo (201 a 222), pela
    // planta de box vendidos de 08/04/2025. Nao aparecem no site publico
    // (app.js so le grupos/terrenos/outros) — sao usados so pelo painel.
    boxes: [
      { box: "101", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "802" },
      { box: "102", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "201" },
      { box: "103", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "201" },
      { box: "104", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "802" },
      { box: "105", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "401" },
      { box: "106", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "1101" },
      { box: "107", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "1001" },
      { box: "108", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "901" },
      { box: "109", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "901" },
      { box: "110", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "801" },
      { box: "111", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "801" },
      { box: "112", vagas: 2, areaPriv: 25.5, status: "disponivel" },
      { box: "113", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "1101" },
      { box: "114", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "1001" },
      { box: "115", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "702" },
      { box: "116", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "602" },
      { box: "117", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "502" },
      { box: "118", vagas: 2, areaPriv: 25, status: "vendido", apto: "403" },
      { box: "201", vagas: 1, areaPriv: 16.26, status: "vendido", apto: "202" },
      { box: "202", vagas: 1, areaPriv: 15, status: "vendido", apto: "202" },
      { box: "203", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "301" },
      { box: "204", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "701" },
      { box: "205", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "701" },
      { box: "206", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "1002" },
      { box: "207", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "1002" },
      { box: "208", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "601" },
      { box: "209", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "601" },
      { box: "210", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "501" },
      { box: "211", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "501" },
      { box: "212", vagas: 1, areaPriv: 12.75, status: "vendido", apto: "301" },
      { box: "213", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "203" },
      { box: "214", vagas: 2, areaPriv: 26.75, status: "vendido", apto: "703" },
      { box: "215", vagas: 2, areaPriv: 26.75, status: "vendido", apto: "503" },
      { box: "216", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "803" },
      { box: "217", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "402" },
      { box: "218", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "902" },
      { box: "219", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "903" },
      { box: "220", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "1003" },
      { box: "221", vagas: 2, areaPriv: 25.5, status: "vendido", apto: "302" },
      { box: "222", vagas: 2, areaPriv: 25, status: "vendido", apto: "603" },
    ],
  },

  {
    id: "quality",
    nome: "Quality Residence",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "residencial",
    status: "pronto",
    statusLabel: "Pronto para morar",
    entrega: "Pronto para morar · Financiável",
    ri: ["RI nº 2-34.244"],
    // Quantos box cada tipologia leva. O painel usa isso para conferir se as
    // vagas fecham com o que ha em estoque. O site nao le este campo.
    vagasPorTipologia: {
      "2 dormitórios c/ móveis": { simples: 1 },
      "2 dormitórios — já alugados": { simples: 1 },
      "3 dormitórios — já alugados": { simples: 1 },
      "3 dormitórios (1 suíte)": { simples: 1 },
    },
    hero: "assets/qual-1.webp",
    folder: "",
    video: "",
    destaque: true,
    tagline: "Piscina, academia e 3 salões de festas — pronto para morar e financiável.",
    localizacao: "Rua Carlos Barbosa, Carazinho/RS.",
    diferenciais: [
      { titulo: "Lazer", desc: "Piscina na área social, junto ao salão de festas." },
      { titulo: "Área fitness", desc: "Academia completa." },
      { titulo: "Salões de festas", desc: "3 salões de festas — dois internos e um externo." },
      { titulo: "Praticidade", desc: "Lavanderia coletiva com área para estender roupas." },
      { titulo: "Acabamento", desc: "Gesso em todo o apartamento, porcelanato e grafiato na parte externa." },
      { titulo: "Segurança", desc: "Hall de entrada e estrutura com segurança." },
    ],
    galeria: [
      { src: "assets/qual-2.webp", legenda: "Piscina" },
      { src: "assets/qual-3.webp", legenda: "Academia" },
      { src: "assets/qual-9.webp", legenda: "Apartamento — living com móveis" },
      { src: "assets/qual-10.webp", legenda: "Dormitório" },
      { src: "assets/qual-4.webp", legenda: "Área social" },
      { src: "assets/qual-5.webp", legenda: "Área social" },
      { src: "assets/qual-6.webp", legenda: "Área social" },
      { src: "assets/qual-7.webp", legenda: "Salão de festas" },
      { src: "assets/qual-8.webp", legenda: "Salão de festas" },
      { src: "assets/qual-planta-57.webp", legenda: "Planta — 2 dormitórios (57m² global)" },
      { src: "assets/qual-planta-69.webp", legenda: "Planta — 2 dormitórios (69m² global)" },
      { src: "assets/qual-planta-3d.webp", legenda: "Planta — 3 dormitórios (1 suíte)" },
      { src: "assets/int-cozinha-1.webp", legenda: "Cozinha com móveis planejados" },
      { src: "assets/qual-map.webp", legenda: "Localização" },
    ],
    grupos: [
      {
        tipo: "2 dormitórios c/ móveis",
        area: "57 m² global · 43 m² privativo",
        garagem: "1 Box de garagem",
        planta: "qual-planta-57",
        unidades: [{ apto: "802A", preco: 430000, status: "disponivel" }],
      },
      {
        tipo: "2 dormitórios c/ móveis",
        area: "69 m² global · 53 m² privativo",
        garagem: "1 Box de garagem",
        planta: "qual-planta-69",
        unidades: [{ apto: "701B", preco: 510000, status: "alugado" }],
      },
      {
        tipo: "2 dormitórios — já alugados",
        area: "69 m² global · 53 m² privativo",
        garagem: "1 Box de garagem",
        planta: "qual-planta-69",
        obs: "Aluguel R$ 1.400,00 · Condomínio e IPTU por conta do inquilino.",
        unidades: [
          { apto: "301B", preco: 470000, status: "alugado" },
          { apto: "601B", preco: 490000, status: "alugado" },
        ],
      },
      {
        tipo: "3 dormitórios — já alugados",
        area: "87 m² global · 66 m² privativo",
        garagem: "1 Box de garagem",
        planta: "qual-planta-3d",
        obs: "Aluguel R$ 1.600,00 · Condomínio e IPTU por conta do inquilino.",
        unidades: [
          { apto: "601A", preco: 590000, status: "alugado" },
          { apto: "801A", preco: 610000, status: "alugado" },
        ],
      },
      {
        tipo: "3 dormitórios (1 suíte)",
        area: "87 m² global · 66 m² privativo",
        garagem: "1 Box de garagem",
        planta: "qual-planta-3d",
        unidades: [
          { apto: "201A", preco: 550000, status: "disponivel" },
          { apto: "401A", preco: 580000, status: "disponivel", tags: ["Semimobiliado"] },
          { apto: "501A", status: "vendido" },
          { apto: "701A", preco: 590000, status: "disponivel" },
        ],
      },
    ],
    // Box do subsolo (01 a 54) e do terreo (55 a 60), pela planta de box
    // vendidos de 10/08/2026. Nao aparecem no site publico — sao usados
    // apenas pelo painel administrativo.
    boxes: [
      { box: "01", vagas: 1, areaPriv: 13.73, status: "disponivel" },
      { box: "02", vagas: 1, areaPriv: 12.25, status: "vendido", apto: "403B" },
      { box: "03", vagas: 1, areaPriv: 12.88, status: "vendido", apto: "504B" },
      { box: "04", vagas: 1, areaPriv: 12.14, status: "vendido", apto: "703A" },
      { box: "05", vagas: 1, areaPriv: 13.55, status: "vendido", apto: "802B" },
      { box: "06", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "202B" },
      { box: "07", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "302B" },
      { box: "08", vagas: 1, areaPriv: 12.65, status: "vendido", apto: "402B" },
      { box: "09", vagas: 1, areaPriv: 12, status: "vendido", apto: "503B" },
      { box: "10", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "204B" },
      { box: "11", vagas: 1, areaPriv: 14.75, status: "vendido", apto: "704B" },
      { box: "12", vagas: 1, areaPriv: 14.15, status: "disponivel" },
      { box: "13", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "604B" },
      { box: "14", vagas: 1, areaPriv: 13.8, status: "vendido", apto: "804B" },
      { box: "15", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "502B" },
      { box: "16", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "602B" },
      { box: "17", vagas: 1, areaPriv: 12.65, status: "vendido", apto: "603B" },
      { box: "18", vagas: 1, areaPriv: 12, status: "vendido", apto: "401B" },
      { box: "19", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "103B" },
      { box: "20", vagas: 1, areaPriv: 14.75, status: "vendido", apto: "203B" },
      { box: "21", vagas: 1, areaPriv: 14.5, status: "vendido", apto: "501B" },
      { box: "22", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "703B" },
      { box: "23", vagas: 1, areaPriv: 13.8, status: "vendido", apto: "803B" },
      { box: "24", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "704A" },
      { box: "25", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "504A" },
      { box: "26", vagas: 1, areaPriv: 12.65, status: "vendido", apto: "201B" },
      { box: "27", vagas: 1, areaPriv: 12, status: "vendido", apto: "303B" },
      { box: "28", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "404B" },
      { box: "29", vagas: 1, areaPriv: 14.75, status: "vendido", apto: "304A" },
      { box: "30", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "702B" },
      { box: "31", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "203A" },
      { box: "32", vagas: 1, areaPriv: 13.8, status: "alugado", apto: "601B" },
      { box: "33", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "204A" },
      { box: "34", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "604A" },
      { box: "35", vagas: 1, areaPriv: 12.65, status: "vendido", apto: "804A" },
      { box: "36", vagas: 1, areaPriv: 12, status: "vendido", apto: "104A" },
      { box: "37", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "502A" },
      { box: "38", vagas: 1, areaPriv: 14.75, status: "vendido", apto: "402A" },
      { box: "39", vagas: 1, areaPriv: 14.15, status: "vendido", apto: "404A" },
      { box: "40", vagas: 1, areaPriv: 14.15, status: "alugado", apto: "301B" },
      { box: "41", vagas: 1, areaPriv: 13.8, status: "vendido", apto: "304B" },
      { box: "42", vagas: 1, areaPriv: 12.84, status: "alugado", apto: "701B" },
      { box: "43", vagas: 1, areaPriv: 12, status: "vendido", apto: "603A" },
      { box: "44", vagas: 1, areaPriv: 12, status: "vendido", apto: "503A" },
      { box: "45", vagas: 1, areaPriv: 12, status: "vendido", apto: "702A" },
      { box: "46", vagas: 1, areaPriv: 12, status: "vendido", apto: "202A" },
      { box: "47", vagas: 1, areaPriv: 12, status: "vendido", apto: "103A" },
      { box: "48", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "602A" },
      { box: "49", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "803A" },
      { box: "50", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "104B" },
      { box: "51", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "501A" },
      { box: "52", vagas: 1, areaPriv: 12.5, status: "alugado", apto: "601A" },
      { box: "53", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "801B" },
      { box: "54", vagas: 1, areaPriv: 12.5, status: "vendido", apto: "403A" },
      { box: "55", vagas: 1, areaPriv: 14.3, status: "vendido", apto: "302A" },
      { box: "56", vagas: 1, areaPriv: 12.25, status: "vendido", apto: "303A" },
      { box: "57", vagas: 1, areaPriv: 12.25, status: "alugado", apto: "801A" },
      { box: "58", vagas: 1, areaPriv: 12.25, status: "disponivel" },
      { box: "59", vagas: 1, areaPriv: 12.25, status: "alugado", obs: "Alugado para o filho do Lairton" },
      { box: "60", vagas: 1, areaPriv: 12.25, status: "disponivel" },
    ],
  },

  {
    id: "nova-vila-rica-iii",
    nome: "Loteamento Nova Vila Rica III",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "terreno",
    status: "obra",
    statusLabel: "Entrega em 2027",
    entrega: "Entrega em 2027",
    ri: [],
    hero: "assets/aerial-vilarica.webp",
    folder: "",
    video: "",
    logo: "assets/nvr3-logo.webp",
    destaque: true,
    tagline: "Lotes prontos para construir, no novo loteamento Nova Vila Rica III.",
    localizacao: "Carazinho/RS — Ruas Laranjeira, Figueira, Jatobá, J. Kennedy e H. T. Schutz.",
    galeria: [
      { src: "assets/nvr3-mapa.webp", legenda: "Mapa de lotes e disponibilidade" },
      { src: "assets/nvr3-urb.webp", legenda: "Projeto de urbanismo" },
      { src: "assets/nvr3-planta.webp", legenda: "Planta de lotes" },
    ],
    terrenos: [
      { quadra: "77", numero: "89", rua: "Laranjeira", area: 348, preco: 90000, status: "vendido" },
      { quadra: "77", numero: "90", rua: "Laranjeira", area: 348, preco: 75000, status: "vendido" },
      { quadra: "77", numero: "91", rua: "Laranjeira", area: 348, preco: 75000 },
      { quadra: "77", numero: "92", rua: "Laranjeira", area: 290, preco: 70000, status: "vendido" },
      { quadra: "77", numero: "93", rua: "Laranjeira", area: 290, preco: 70000 },
      { quadra: "77", numero: "94", rua: "Laranjeira", area: 290, preco: 70000, status: "vendido" },
      { quadra: "77", numero: "95", rua: "Laranjeira", area: 290, preco: 65000, status: "vendido" },
      { quadra: "77", numero: "96", rua: "Laranjeira", area: 290, preco: 65000, status: "vendido" },
      { quadra: "77", numero: "97", rua: "Laranjeira", area: 290, preco: 65000, status: "vendido" },
      { quadra: "77", numero: "98", rua: "Laranjeira", area: 348, preco: 75000 },
      { quadra: "77", numero: "99", rua: "Laranjeira", area: 290, preco: 63000, status: "vendido" },
      { quadra: "77", numero: "100", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "101", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "103", rua: "Laranjeira", area: 262, preco: 75000 },
      { quadra: "77", numero: "104", rua: "Laranjeira", area: 314.4, preco: 85000 },
      { quadra: "77", numero: "105", rua: "Laranjeira", area: 468, preco: 115000 },
      { quadra: "77", numero: "106", rua: "Figueira", area: 312, preco: 85000 },
      { quadra: "77", numero: "107", rua: "Figueira", area: 312, preco: 85000 },
      { quadra: "147", numero: "15", rua: "Laranjeira", area: 348, preco: 90000, status: "vendido" },
      { quadra: "147", numero: "16", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "17", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "18", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "19", rua: "Laranjeira", area: 290, preco: 80000, status: "vendido" },
      { quadra: "147", numero: "20", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "21", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "22", rua: "Laranjeira", area: 290, preco: 90000 },
      { quadra: "147", numero: "23", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "24", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "25", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "26", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "27", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "28", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "29", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "30", rua: "Laranjeira", area: 290, preco: 95000 },
      { quadra: "147", numero: "31", rua: "Laranjeira", area: 351.78, preco: 105000, status: "vendido" },
      { quadra: "147", numero: "32", rua: "J. Kennedy", area: 345.72, preco: 95000, status: "vendido" },
      { quadra: "155", numero: "1", rua: "J. Kennedy", area: 445.5, preco: 115000 },
      { quadra: "155", numero: "2", rua: "Jatobá", area: 270, preco: 70000, status: "vendido" },
      { quadra: "155", numero: "3", rua: "Jatobá", area: 270, preco: 70000, status: "vendido" },
      { quadra: "155", numero: "4", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "5", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "6", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "7", rua: "Jatobá", area: 270, preco: 70000, status: "vendido" },
      { quadra: "155", numero: "8", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "9", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "12", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "13", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "14", rua: "Jatobá", area: 270, preco: 75000 },
      { quadra: "155", numero: "15", rua: "Jatobá", area: 324, preco: 90000 },
      { quadra: "155", numero: "16", rua: "Laranjeira", area: 324, preco: 100000 },
      { quadra: "155", numero: "17", rua: "Laranjeira", area: 270, preco: 85000 },
      { quadra: "155", numero: "18", rua: "Laranjeira", area: 270, preco: 85000 },
      { quadra: "155", numero: "19", rua: "Laranjeira", area: 270, preco: 75000, status: "vendido" },
      { quadra: "155", numero: "22", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "23", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "24", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "25", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "26", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "27", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "28", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "29", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "30", rua: "Laranjeira", area: 270, preco: 90000 },
      { quadra: "155", numero: "31", rua: "J. Kennedy", area: 423.9, preco: 115000 },
      { quadra: "157", numero: "16", rua: "H. T. Schutz", area: 360, preco: 120000 },
      { quadra: "157", numero: "19", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "20", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "21", rua: "Jatobá", area: 265, preco: 95000 },
      { quadra: "157", numero: "22", rua: "Jatobá", area: 323.35, preco: 115000 },
      { quadra: "157", numero: "23", rua: "J. Kennedy", area: 357.6, preco: 100000 },
      { quadra: "157", numero: "24", rua: "J. Kennedy", area: 250.85, preco: 95000 },
      { quadra: "157", numero: "25", rua: "Laranjeira", area: 297.6, preco: 115000 },
      { quadra: "157", numero: "26", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "27", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "28", rua: "Laranjeira", area: 265, preco: 85000 },
      { quadra: "157", numero: "29", rua: "Laranjeira", area: 205, preco: 65000 },
      { quadra: "157", numero: "30", rua: "Laranjeira", area: 205, preco: 60000, status: "vendido" },
      { quadra: "157", numero: "31", rua: "Laranjeira", area: 327.6, preco: 85000, status: "vendido" },
      { quadra: "157", numero: "32", rua: "Laranjeira", area: 336, preco: 85000, status: "vendido" },
      { quadra: "157", numero: "33", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "34", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "35", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "36", rua: "Laranjeira", area: 336, preco: 95000 },
      { quadra: "157", numero: "37", rua: "J. Kennedy", area: 333.45, preco: 115000 },
    ],
    grupos: [],
  },

  {
    id: "nova-vila-rica",
    nome: "Loteamento Nova Vila Rica I & II",
    confirmado: true,
    cidade: "Carazinho/RS",
    categoria: "terreno",
    status: "pronto",
    statusLabel: "Prontos para construir",
    entrega: "Prontos para construir · Financiáveis MCMV I & II",
    ri: [],
    hero: "assets/aerial-vilarica-i-ii.webp",
    folder: "",
    video: "",
    galeria: [],
    terrenos: [
      { lote: "Nova Vila Rica I", quadra: "144", numero: "01", rua: "Alberto Graeff", area: 325, preco: 125000 },
      { lote: "Nova Vila Rica I", quadra: "145", numero: "01", rua: "Alberto Graeff", area: 345, preco: 125000 },
      { lote: "Nova Vila Rica I", quadra: "145", numero: "03", rua: "Alberto Graeff", area: 320, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "146", numero: "01", rua: "Figueira", area: 385, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "147", numero: "09", rua: "Alberto Graeff", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica I", quadra: "147", numero: "05", rua: "Alberto Graeff", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "77", numero: "50", rua: "Acácia", area: 342, preco: 100000 },
      { lote: "Nova Vila Rica II", quadra: "77", numero: "51", rua: "Acácia", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "145", numero: "10", rua: "Acácia", area: 400, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "145", numero: "18", rua: "Figueira", area: 300, preco: 95000 },
      { lote: "Nova Vila Rica II", quadra: "146", numero: "22", rua: "Figueira", area: 1420, preco: 305000 },
    ],
    grupos: [],
  },

  {
    id: "outros",
    nome: "Outros Imóveis",
    confirmado: true,
    cidade: "Santa Maria/RS · Carazinho/RS",
    categoria: "outros",
    status: "pronto",
    statusLabel: "Disponível",
    entrega: "Pronto",
    ri: [],
    hero: "assets/gabro-predio.webp",
    galeria: [],
    outros: [
      {
        nome: "Residencial Gabro",
        local: "Centro de Santa Maria/RS",
        descricao:
          "Apto 604 — 2 dormitórios, sala de estar com sacada, cozinha integrada com lavanderia, churrasqueira e box de garagem nº 38. Posição lateral com sol da manhã.",
        area: "82 m² global · 60 m² privativo",
        preco: 475000,
        precoPrefixo: "de",
        status: "disponivel",
      },
      {
        nome: "Edifício Campos Elísios",
        local: "Centro de Carazinho/RS",
        descricao:
          "3 dormitórios (1 suíte com closet), 2 banheiros, 3 sacadas, copa, cozinha, churrasqueira e despensa. Edifício de esquina, excelente localização, a uma quadra da avenida. Box duplo.",
        area: "145 m² privativo",
        preco: 495000,
        status: "alugado",
        obs: "Alugado por R$ 2.400,00.",
      },
      {
        nome: "Terreno Loteamento Jardim América",
        local: "Não-Me-Toque/RS",
        descricao:
          "Em frente à Stara, saída para Lagoa dos 3 Cantos. Na 2ª quadra, com linda vista do alto do loteamento. Quadra 490, Lote 241, 16m x 24,75m.",
        area: "396 m²",
        preco: 148000,
        status: "disponivel",
      },
      {
        nome: "Terreno Bairro Vila Aurora",
        local: "Carazinho/RS",
        descricao:
          "Altos da Princesa com Vila Rica, a uma quadra da Siqueira Campos, perto do posto de combustível. Fundos e uma das laterais já com muro. Rua do Carmo, 13m x 33m.",
        area: "429 m²",
        preco: 135000,
        status: "disponivel",
      },
    ],
    grupos: [],
  },
];

// Localização (link Google Maps) por empreendimento
const LOCAIS = {
  quality: { mapsUrl: "https://www.google.com/maps?q=-28.287054,-52.797171" },
  prime: { mapsUrl: "https://www.google.com/maps?q=R.%20Ven%C3%A2ncio%20Aires%2C%20121%2C%20Centro%2C%20Carazinho%20-%20RS" },
  renaissance: { mapsUrl: "https://www.google.com/maps?q=R.%20Ven%C3%A2ncio%20Aires%2C%20Centro%2C%20Carazinho%20-%20RS" },
  personalite: { mapsUrl: "https://www.google.com/maps?q=-28.284667,-52.791722" },
  evolutti: { mapsUrl: "https://www.google.com/maps?q=-28.282806,-52.784389" },
  boulevard: { mapsUrl: "https://www.google.com/maps?q=Pra%C3%A7a%20General%20Os%C3%B3rio%2C%20Ibirub%C3%A1%20-%20RS" },
  "premium-office": { mapsUrl: "https://www.google.com/maps?q=-28.283750,-52.796917" },
};

window.SENGER = { META, EMPREENDIMENTOS, LOCAIS };

